### ISSUE TITLE
Plexbmc as default libary

### ISSUE THREAD

**Issue by damianeickhoff** [hippojay/plugin.video.plexbmc#110]
Hi,

Is it possible to set Plexbmc as a default libary? That when u start Kodi, you get to see the content thats running on Plex. Or maybe icons in the menu that when u select TV Shows, you automaticaly go to TV Shows on the Plex server etc? That would be very nice, because now I have to select add-ons etc. 

Kind Regards

**Comment by Rockycjc** [comment]
Sounds like you need to switch to the amber skin so that you can select "TV
Shows" right in the main home screen as opposed to going through Add Ons.

**Comment by joswart** [comment]
Apart from switching to Amber, you could also customize most skins, so they include plugins in the main menu. Amber has done that for you.

**Comment by hippojay** [comment]
Yes, best bet is amber skin.  Kodi doesn't allow the default library to be populated without some serious heavy lifting and a lack of some plex specific features.
