### ISSUE TITLE
Network not ready after boot

### ISSUE THREAD

**Issue by arnold-maderthaner** [hippojay/plugin.video.plexbmc#111]
Hi !

I have plexbmc running on a new installed kodibuntu server with the amber skin. my setup is configured so that the plex libary is shown right after bootup. 
my issue is that the library isn't show after booting as the network isn't initialized at that point in time.

Here the log that I get: 

10:05:30 T:139957072328448   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
10:05:30 T:139957072328448   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
10:05:30 T:139955451975424  NOTICE: PleXBMC -> Reading settings configuration
10:05:30 T:139955451975424  NOTICE: PleXBMC -> Running PleXBMC: 3.6.1
10:05:30 T:139955451975424  NOTICE: Waking Servers with WOL
10:05:30 T:139955451975424  NOTICE: PleXBMC -> Debug is turned off.  Running silent
10:05:30 T:139955460368128  NOTICE: PleXBMC.plexserver -> talk : Server: 10.0.0.9 is offline or uncontactable. error: ('Connection aborted.', error(101, 'Network is unreachable'))
10:05:30 T:139955460368128  NOTICE: PleXBMC.plexserver -> talk : Server: 62.178.50.227 is offline or uncontactable. error: ('Connection aborted.', error(101, 'Network is unreachable'))
10:05:30 T:139955460368128  NOTICE: PleXBMC.plexserver -> talk : Server: 78.46.101.201 is offline or uncontactable. error: ('Connection aborted.', error(101, 'Network is unreachable'))
10:05:30 T:139957072328448   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
10:05:30 T:139957072328448   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
10:05:30 T:139955451975424  NOTICE: ===== PLEXBMC STOP: 0.412989139557 seconds =====
10:05:30 T:139955460368128  NOTICE: PleXBMC.plex -> talk_to_myplex : myplex: https://plex.tv is offline or uncontactable. error: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
10:05:30 T:139955460368128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'link' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plexbmc.py", line 4081, in start_plexbmc
                                                amberskin()
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plexbmc.py", line 3005, in amberskin
                                                root = plex_network.get_myplex_queue()
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plex.py", line 174, in get_myplex_queue
                                                return self.get_processed_myplex_xml('/pms/playlists/queue/all')
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plex.py", line 118, in get_processed_myplex_xml
                                                data = self.talk_to_myplex (url)
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plex.py", line 265, in talk_to_myplex
                                                return link
                                            UnboundLocalError: local variable 'link' referenced before assignment
                                            -->End of Python script error report<--
10:05:31 T:139957072328448   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
10:05:31 T:139957072328448   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
10:05:31 T:139957072328448   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)

Does anyone have a tip how to fix that issue ?

**Comment by forouher** [comment]
A quick workaround would be to simply delay the start of kodi until the network is up.

But yeah, the better solution would be that plexbmc updates it's server connections from time to time.
