### ISSUE TITLE
Subtitles won't work when streaming "Shared Content" videos

### ISSUE THREAD

**Issue by cassioac** [hippojay/plugin.video.plexbmc#114]
Steps to reproduce:

Connect using MyPlex account with access to "Shared Content" items from another account, play any video which does have subtitles on the original account server.

Already tried with different skins (Amber and Mimic) and different PLEXBMC settings

Subtitles works with original account connected instead of account with shared access

Tested on PleXBMC V4.0.0~beta4

EDIT: As a workaround, if I select the subtitle before starting the video (from context menu) it works, but that method is too bad as the context menu is not available in most remotes. If I try to select the subtitle after video is started it just states "NONE" as subtitle.

**Comment by cassioac** [comment]
Also even when not using a shared account (if main account is used) we have to stop / play the video a couple of times so the subtitles enter as external source on the video.

**Comment by cassioac** [comment]
Hi @hippojay , do you think this can be fixed somewhere in the future?

Thanks

**Comment by hippojay** [comment]
i've noticed that sometimes subtitles do not kick in.  KODI is (or was, I need to check the most recent version) not that good at allowing the right subs to be selected automatically (or at least without having to go through the menu to manually add them).

I'll do some more checking on this.

**Comment by cassioac** [comment]
I'm not a developer so I'm sorry if I'm saying nonsense, but emby addon gets the subtitles 100% of the time when using emby server...

**Comment by hippojay** [comment]
Cheers - I'll go and hunt through their code, to see if they have a better way of doing it (although Ebmy addon input the data into the kodi native library, which might make a difference)
