### ISSUE TITLE
Rescan Library not working

### ISSUE THREAD

**Issue by arnold-maderthaner** [hippojay/plugin.video.plexbmc#115]
Hi !

When I try to send a "Refresh Library" Command to my Plex server I get the following exception in kodi.log:

19:52:32 T:140036108437248  NOTICE: PleXBMC -> Debug is turned off.  Running silent
19:52:32 T:140036108437248  NOTICE: PleXBMC -> Detected parameters: {'url': 'http://10.0.0.9:32400/library/sections/2/recentlyAdded', 'mode': '0'}
19:52:32 T:140035319916288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 39: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plexbmc.py", line 4081, in start_plexbmc
                                                amberskin()
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plexbmc.py", line 3036, in amberskin
                                                fullShelf (server_list)
                                              File "/home/nuc/.kodi/addons/plugin.video.plexbmc-3.6.1/resources/lib/plexbmc.py", line 3244, in fullShelf
                                                printDebug.debug(" Building Recent window title: %s\n    Building Recent window url: %s\n    Building Recent window thumb: %s" % (title_name, title_url, title_thumb))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 39: ordinal not in range(128)
                                            -->End of Python script error report<--
19:52:32 T:140035319916288  NOTICE: Thread BackgroundLoader start, auto delete: false
19:52:32 T:140036108437248  NOTICE: ===== PLEXBMC STOP: 0.442992925644 seconds =====
19:52:32 T:140035319916288  NOTICE: Thread FileCache start, auto delete: false

**Comment by hippojay** [comment]
Non-ascii chars are the bane of my life on plexbmc.  I fix them in one place and it breaks elsewhere.

It should be really straight forward (and changed in Python 3).  I'll see if I can track it down.
