### ISSUE TITLE
Hostname vs IP address bug

### ISSUE THREAD

**Issue by chronaden** [hippojay/plugin.video.plexbmc#116]
I did my first reinstall (to newest version of PlexBMC) in 6 months, going from Openelec to OSMC. I had major issues regarding communicating with my PMS (running on Synology 214play). I could see the medie on the front screen, it even updated when I made changes to PMS, but when I clicked the media, I just got an empty folder, no matter if we were talking movies, series, music or whatever.

Two days later, I random try to input IP adress instead of the hostname that worked before my re-install, and now it is working perfectly. This was tested on both a rPi1 and rPi2, and going back to Openelec produced the same effect.

Can anyone confirm this bug?

**Comment by dowdian** [comment]
I can confirm this in version 3.6.1 and 4.0.0 Beta 4 on Kodi 14.2 on a rPi2. I am so glad you posted this! It was driving me crazy trying to figure out why I could get some content to display, like the Recently Added and On Deck on the front screen, but couldn't get anything to stream nor get anything else to show. By changing to the IP address, everything seems to be working as expected

**Comment by chronaden** [comment]
Nice to know I'm not the only one :)

**Comment by Janrabbit** [comment]
I'm having this same issue. I have tried changing to IP however still no joy. Do you put the IP in the manual server set-up and in the section where it says master server?

**Comment by chronaden** [comment]
IP in manual server setup, and then the name of the server in master server.

**Comment by hippojay** [comment]
never tested with dns resolution, as the manual config has always been assumed to be IP address.  I'll check it out.

**Comment by hippojay** [comment]
Added a fix for FQDNs in plexbmc.
