### ISSUE TITLE
Getting an error when plexbmc is trying to find server

### ISSUE THREAD

**Issue by kamcknig** [hippojay/plugin.video.plexbmc#118]
This seemed to be working just fine yesterday, nothing about my setup that I know of has changed but now I'm getting an exception thrown from one of the python scripts

    18:19:14 T:30396   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-3.4.5\default.py", line 5281, in <module>
                                                setMasterServer()
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-3.4.5\default.py", line 5148, in setMasterServer
                                                servers=getMasterServer(True)
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-3.4.5\default.py", line 2582, in getMasterServer
                                                for serverData in discoverAllServers().values():
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-3.4.5\default.py", line 307, in discoverAllServers
                                                local_server = getLocalServers(das_host, das_port)
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-3.4.5\default.py", line 411, in getLocalServers
                                                server=etree.fromstring(html)
                                              File "<string>", line 123, in XML
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--

**Comment by hippojay** [comment]
Kyle,

Plexbmc 3.4.5 has a strange problem when using one of the inbuilt Python functions. It would be better if you switched to the latest v4 beta as this fixes this and other known issues. 



Thanks
---
Dave H-J

Sent on the move, so please excuse any typos.

**Comment by kamcknig** [comment]
I've switched to the newest plexbmc but am still getting errors :/

08:53:39 T:51036  NOTICE: ===== PLEXBMC START [id: 1439643219.12] =====
08:53:39 T:51036  NOTICE: PleXBMC -> Reading settings configuration
08:53:39 T:51036  NOTICE: PleXBMC -> Running PleXBMC: 4.0.0~beta4
08:53:39 T:51036  NOTICE: PleXBMC -> Script argument is ['default.py', 'managemyplex']
08:53:39 T:51036  NOTICE: PleXBMC -> Running Python: sys.version_info(major=2, minor=7, micro=8, releaselevel='final', serial=0)
08:53:39 T:51036  NOTICE: PleXBMC -> CWD is set to: C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix
08:53:39 T:51036  NOTICE: PleXBMC -> Platform: Windows
08:53:39 T:51036  NOTICE: PleXBMC -> Setting debug: info
08:53:39 T:51036  NOTICE: PleXBMC -> FullRes Thumbs are set to: False
08:53:39 T:51036  NOTICE: PleXBMC -> Settings streaming: 0
08:53:39 T:51036  NOTICE: PleXBMC -> Setting filter menus: True
08:53:39 T:51036  NOTICE: PleXBMC -> Flatten is: 0
08:53:39 T:51036  NOTICE: PleXBMC -> Setting stream Control to : PLEX CONTROL
08:53:39 T:51036  NOTICE: PleXBMC -> Force DVD playback: False
08:53:39 T:51036  NOTICE: PleXBMC -> SMB IP Override: False
08:53:39 T:51036  NOTICE: setting: nasoverrideip is :
08:53:39 T:51036  NOTICE: PleXBMC -> NAS IP:
08:53:40 T:49176  NOTICE: Thread LanguageInvoker start, auto delete: false
08:53:40 T:49176  NOTICE: -->Python Interpreter Initialized<--
08:53:40 T:49176  NOTICE: ===== PLEXBMC START [id: 1439643220.49] =====
08:53:40 T:49176  NOTICE: PleXBMC -> Reading settings configuration
08:53:40 T:49176  NOTICE: PleXBMC -> Running PleXBMC: 4.0.0~beta4
08:53:40 T:49176  NOTICE: PleXBMC -> Script argument is ['default.py', 'signin']
08:53:40 T:49176  NOTICE: PleXBMC -> Running Python: sys.version_info(major=2, minor=7, micro=8, releaselevel='final', serial=0)
08:53:40 T:49176  NOTICE: PleXBMC -> CWD is set to: C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix
08:53:40 T:49176  NOTICE: PleXBMC -> Platform: Windows
08:53:40 T:49176  NOTICE: PleXBMC -> Setting debug: info
08:53:40 T:49176  NOTICE: PleXBMC -> FullRes Thumbs are set to: False
08:53:40 T:49176  NOTICE: PleXBMC -> Settings streaming: 0
08:53:40 T:49176  NOTICE: PleXBMC -> Setting filter menus: True
08:53:40 T:49176  NOTICE: PleXBMC -> Flatten is: 0
08:53:40 T:49176  NOTICE: PleXBMC -> Setting stream Control to : PLEX CONTROL
08:53:40 T:49176  NOTICE: PleXBMC -> Force DVD playback: False
08:53:40 T:49176  NOTICE: PleXBMC -> SMB IP Override: False
08:53:40 T:49176  NOTICE: setting: nasoverrideip is :
08:53:40 T:49176  NOTICE: PleXBMC -> NAS IP:
08:53:40 T:51036  NOTICE: PleXBMC.plex -> talk_to_myplex : url = https://plex.tv/users/account
08:53:40 T:51036   ERROR: C:\Users\kamck\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
08:53:40 T:49176  NOTICE: PleXBMC.plex -> talk_to_myplex : url = https://plex.tv/pins.xml
08:53:41 T:49176   ERROR: C:\Users\kamck\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
08:53:42 T:51036  NOTICE: HTTP response error: 422
08:53:42 T:51036   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plexbmc.py", line 4105, in start_plexbmc
                                                manage_window.start()
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plex_signin.py", line 242, in start
                                                self.gather_plex_information()
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plex_signin.py", line 247, in gather_plex_information
                                                user = self.plex_network.get_myplex_information()
                                              File "C:\Users\kamck\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plex.py", line 624, in get_myplex_information
                                                date= xml.find('joined-at').text
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--

**Comment by hippojay** [comment]
Fixed - handle this myplex data error more gracefully.
