### ISSUE TITLE
KODI Isengard Freeze

### ISSUE THREAD

**Issue by Rockycjc** [hippojay/plugin.video.plexbmc#119]
I upgraded one of my boxes to KODI 15 and found that while plexbmc setup is flawless and media plays, KODI will freeze the box entirely after 15 to 20 minutes.  I've read nothing about this on any other forums for the matricom g box, kodi, or plexbmc so not sure where the root cause is.  I haven't pulled the logs because the tv I was using was the LivingRoom so the wife made me pit it back on 14.2 so the issue would stop happening.  I can try putting it on another box to see if it makes a difference and try to pull the log but I wanted to see if anyone else has experienced tthis.

**Comment by hippojay** [comment]
I'll see if I can get some testing done, but it won't be for a few weeks unfortunately (29/30 August). I notice that there is a 15.1 RC which is fairly quick, so perhaps it's a known issue. 

Thanks
---
Dave H-J

Sent on the move, so please excuse any typos.

**Comment by Rockycjc** [comment]
Unfortunately the issue persists with 15.1 RC and Stable.  So if it is a KODI issue they are not aware or are not paying attention with it.  I still need to grab logs which I will try and do and post here after I get them.

**Comment by Rockycjc** [comment]
Here is the very end of my the latest log.  if you want me to paste the entire thing I can but it is about 25000 + rows, so I figure the very end with the warning and errors should suffice.

23:51:35 T:2027223056  NOTICE: ===== PLEXBMC STOP [id: 1440301885.48]: 10.0472259521 seconds =====
23:51:49 T:1789681632  NOTICE: stopping zeroconf publishing
23:51:49 T:1789681632  NOTICE: stop sap announcement listener
23:51:49 T:1789681632  NOTICE: clean cached files!
23:51:49 T:1789681632  NOTICE: unload skin
23:51:49 T:1851076616 WARNING: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.skin.widgets/default.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.skin.widgets/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6WindowE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N14PythonBindings30XBMCAddon_xbmc_Player_DirectorE
23:51:49 T:1789681632  NOTICE: stopped
23:51:49 T:1789681632  NOTICE: destroy
23:51:50 T:1789681632  NOTICE: closing down remote control service
23:51:50 T:1789681632  NOTICE: unload sections
23:51:50 T:1789681632  NOTICE: special://profile/ is mapped to: special://masterprofile/
23:51:50 T:1789681632  NOTICE: destroy
23:51:50 T:1789681632 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
23:51:50 T:1789681632 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
23:51:50 T:1789681632  NOTICE: closing down remote control service
23:51:50 T:1789681632  NOTICE: unload sections
23:51:50 T:1789681632  NOTICE: application stopped...

**Comment by Rockycjc** [comment]
Hippojay....have you left us :-( ?

**Comment by hippojay** [comment]
Not yet!  Work has ramped up to an extreme amount and I find I have zero free time!   It's pretty frustrating because there are things I want to do on this but no chunks of time to do it. 

This won't go on forever though, but it could be another month or so. Any more than that and I'll be looking at more drastic solutions to cutting my hours!!

Sorry this isn't the reply you were looking for.   I want to continue plexbmc as I actually enjoy doing it.  At the moment I just need 28 hour days :-(

I'll keep you updated as things progress.

**Comment by cassioac** [comment]
What plexbmc version are you using? I use the v4 beta4 flawlessly with isengard 15 and 15.1, in android, kodibunto, openelec, whatever. Never experienced that problem.

**Comment by jeiai** [comment]
Cassioac please help... I have android kodi 15.1 can not run propperly plexmbc...

I downloaded 4 beta 4!!! Not working all i get is myplex queue, signout and refresh data...

And in cant do nothing please help...


Jeiai1978@gmail.com

**Comment by jeiai** [comment]
![screenshot_2015-10-20-08-39-07](https://cloud.githubusercontent.com/assets/15215502/10610902/09dda78e-7707-11e5-81ff-474f6f0c007f.png)

**Comment by cassioac** [comment]
Have you made login to myplex in plexbmc?

Is your plex server also logged into myplex?

Enviado do meu iPhone

Em 20 de out de 2015, ?s 12:46, jeiai <notifications@github.com<mailto:notifications@github.com>> escreveu:


Cassioac please help... I have android kodi 15.1 can not run propperly plexmbc...

I downloaded 4 beta 4!!! Not working all i get is myplex queue, signout and refresh data...

And in cant do nothing please help...

Jeiai1978@gmail.com<mailto:Jeiai1978@gmail.com>

-

**Comment by jeiai** [comment]
Y es... I logged in


How do i log in muy server to muy plex...?

**Comment by Rockycjc** [comment]
The last few posts should really be in a separate bug.  The current bug is related to a working installation and connection to the server but an issue with KODI freezing up after a period of use.

Please post a new bug with your issue.

**Comment by Rockycjc** [comment]
HIPPOJAY!!!  Where have you been buddy?  Its been over a month since I last asked when you'd be back to tackle all the submitted issues.  Can you give us an update on your whereabouts?

**Comment by cassioac** [comment]
What's your server OS?

Anyway, you log it in through the web interface, in the server settings..

Enviado do meu iPhone

Em 20 de out de 2015, ?s 13:31, jeiai <notifications@github.com<mailto:notifications@github.com>> escreveu:


Y es... I logged in

How do i log in muy server to muy plex...?

-

**Comment by cassioac** [comment]
Usually you access it through http://serverip:32400/web

Enviado do meu iPhone

Em 20 de out de 2015, ?s 13:31, jeiai <notifications@github.com<mailto:notifications@github.com>> escreveu:


Y es... I logged in

How do i log in muy server to muy plex...?

-

**Comment by hippojay** [comment]
@Rockycjc are you still getting freezing?  I've been using isengard a little bit the past few days, and the only odd behaviour I have seen is the amber skin breaking (i don;t think i'm on the latest version, so probably a helix to isengard issue)

**Comment by Rockycjc** [comment]
@hippojay I don't get freezing currently because I downgraded back to Helix.  It is definitely an issue that occurs with Isengard but I figure you are the only one that is going to fix or handle the issue.  Are you able to see anything in the log that I had posted.

**Comment by hippojay** [comment]
@Rockycjc nothing in you log extract I'm afraid. It just looked like a normal kodi exit sequence.   It could be the androidness of it.  It's not a platform that I have ever tested against.  I do have some android tablets, so perhaps I can get one of these up and running with kodi and check it out. 

I only have kitkat thought, if this is lollipop then I won't be able to check.
