### ISSUE TITLE
Issue with Foreign Characters in File Names

### ISSUE THREAD

**Issue by TMDaines** [hippojay/plugin.video.plexbmc#120]
I've brought up on a couple of occasions on the Plex forums the fact that PleXBMC does not seem to properly handle files that have foreign characters in their file name. I thought I would do a little digging in the logs in an attempt to highlight the cause and hopefully enable somebody to suggest some settings that I need to change or they can address a bug in the PleXBMC code.

The issue is that as files with foreign characters are not being addressed correctly, properly named and stored subtitles are often not being detected and files are also not being open in players other than Kodi's default DVDPlayer.

First of all it's worth addressing that I have no issues with these files either in Plex in general or when loaded in the Kodi libary. Both other Plex clients and Kodi have no issues finding the subtitles for these films and loading them. The issue here is most definitely with PleXBMC or with some settings that may be adversely affecting its proper working.

In the following log (http://xbmclogs.com/pht71otgk), I have launched Kodi w/ PleXBMC and played five different files. The first four files have foreign characters in their file name; the fifth and final file does not. If you search for "PleXBMC -> selectMedia : == ENTER ==" you will find the lines where I open each file. These are:
- 2700 (foreign chars)
- 4308 (foreign chars)
- 5866 (foreign chars)
- 7631 (foreign chars)
- 9153 (only standard chars)

For each of the first four files, you will see something like this:

15:31:03 T:3688  NOTICE: PleXBMC -> selectMedia : == ENTER ==
15:31:03 T:3688  NOTICE: PleXBMC -> mediaType : Detected windows source file
15:31:03 T:3688  NOTICE: PleXBMC -> mediaType : Checking for local file
15:31:03 T:3688  NOTICE: PleXBMC -> mediaType : No local file
15:31:03 T:3688  NOTICE: PleXBMC -> selectMedia : We have selected media at http://192.168.0.20:32400/library/parts/10891/file.mkv?X-Plex-Platform=KODI&X-Plex-Model=unknown&X-Plex-Client-Platform=KODI&X-Plex-Client-Identifier=8d0cb2e0-7d03-435a-87f0-ed049d57eace&X-Plex-Device=PleXBMC&X-Plex-Product=PleXBMC&X-Plex-Platform-Version=Windows&X-Plex-Language=en&X-Plex-Device-Name=My+PleXBMC+Client&X-Plex-Provides=player&X-Plex-Version=4.0.0%7Ebeta4

For the file with no foreign chars, you will see the following:

15:32:07 T:4100  NOTICE: PleXBMC -> selectMedia : == ENTER ==
15:32:07 T:4100  NOTICE: PleXBMC -> mediaType : Detected windows source file
15:32:07 T:4100  NOTICE: PleXBMC -> mediaType : Checking for local file
15:32:07 T:4100  NOTICE: PleXBMC -> mediaType : Local file found, will use this
15:32:07 T:4100  NOTICE: PleXBMC -> selectMedia : We have selected media at file:E:\Film & TV\Film\Archive\Benny's Video (1992)\Benny's Video (1992).mkv

The issue appears to be the fact that PleXBMC is not able to find files locally when they have a foreign character in the name. Can anyone suggest how to resolve this issue?

**Comment by TMDaines** [comment]
No-one able to help? Doesn anyone need any further information to be able to resolve this?

**Comment by TMDaines** [comment]
I would some help with issue. I cannot imagine it is that complicated to resolve, if you know what you are doing. As you can see above, Plex's provides a url when opening a file with non-standard characters, but uses the filepath when all the characters in the file name are standard. This is a massive pain.

**Comment by hippojay** [comment]
Non-ascii chars are reasonably difficult to fix - which I believe is one of the major issues addressed in  python 3.  All data should be encoded when it comes into plexbmc, 

The log file has since been rotated out of xbmclogs - so if you could upload another one I will have a look for you.

**Comment by TMDaines** [comment]
Here is another log where this behaviour is exhibited: [http://goo.gl/J1jQCU](url)

Search for "We have selected media at" to see the behaviour when PleXBMC attempts to pay a file with a foreign character in its title and then one without.

**Comment by TMDaines** [comment]
I've switched over to Emby right now as this issue is a bit of a deal breaker. Please look into fixing this and then I can come back!

**Comment by saqebakhter** [comment]
How is emby vs plex.

TMDaines wrote:
>
> I've switched over to Emby right now as this issue is a bit of a deal 
> breaker. Please look into fixing this and then I can come back!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hippojay/plugin.video.plexbmc/issues/120#issuecomment-178650594>.
>

-- 
--Saqeb

**Comment by TMDaines** [comment]
I have only just switched over so cannot really say. Plex seems a lot more mature than Emby at the moment, but their Kodi integration is much stronger. In all honesty the main reason I'm switching is because of this issue with PleXMBC not working properly with files with foreign characters. It makes using DSPlayer Kodi impossible.

**Comment by russell** [comment]
Hey, I have hit a similar issue

```
15:22:39 7490.733887 T:1409475648  NOTICE: ===== PLEXBMC STOP [id: 1454905356.6]: 3.16621685028 seconds =====
15:22:40 7491.350098 T:1429206080   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
15:22:40 7491.351074 T:1429206080   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
15:22:41 7492.477051 T:1429206080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 58: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 4120, in start_plexbmc
                                                amberskin()
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 2962, in amberskin
                                                fullShelf (server_list)
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 3197, in fullShelf
                                                printDebug.debug(" Building Recent window title: %s\n    Building Recent window url: %s\n    Building Recent window thumb: %s" % (title_name, title_url, title_thumb))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 58: ordinal not in range(128)
                                            -->End of Python script error report<--

```

**Comment by russell** [comment]
I have a fix for the error above here, https://github.com/russell/plugin.video.plexbmc/commit/837181b0a27ff5c021fe3d3f6bb4f56e3bed74b1

What branch should i be committing against to submit fixes?
