### ISSUE TITLE
Cannot login using 4.* beta

### ISSUE THREAD

**Issue by TheFatherMind** [hippojay/plugin.video.plexbmc#122]
I found lots of mentions of this while doing a google.  I was surprised not to find it here.
I even found a long ass thread about it on reddit: https://www.reddit.com/r/kodi/comments/2z6mih/plexbmc_script_failed/

I am using Kodi 15.1
When using PlexBMC v3.6.1 I can code my login info into the config page and everything works great!
But when I upgrade past that the "Sign In" menu option does not work.  I get a script error.
Since I am new to Plex I had to actually downgrade to solve this.  Took me a while to work that out.

Here is some info from my logs...
NOTICE: ===== PLEXBMC STOP [id: 1441006814.74]: 0.541184902191 seconds =====
NOTICE: Thread LanguageInvoker start, auto delete: false
ERROR: GetDirectory - Error getting plugin://plugin.video.plexbmc/?mode=0&url=cmd%3asignintemp
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexbmc/?mode=0&url=cmd%3asignintemp) failed
NOTICE: Thread LanguageInvoker start, auto delete: false
NOTICE: -->Python Interpreter Initialized<--
NOTICE: ===== PLEXBMC START [id: 1441006815.53] =====

NOTICE: ===== PLEXBMC START [id: 1441006815.96] =====
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named pyxbmct.addonwindow
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.video.plexbmc-4.0.0~beta4/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/home/user/.kodi/addons/plugin.video.plexbmc-4.0.0~beta4/resources/lib/plexbmc.py", line 4080, in start_plexbmc
                                                import plex_signin
                                              File "/home/user/.kodi/addons/plugin.video.plexbmc-4.0.0~beta4/resources/lib/plex_signin.py", line 1, in <module>
                                                import pyxbmct.addonwindow as pyxbmct
                                            ImportError: No module named pyxbmct.addonwindow
                                            -->End of Python script error report<--
NOTICE: PleXBMC -> Reading settings configuration

**Comment by hippojay** [comment]
pyxbmct is a further kodi addon dependancy - which should be loaded at instal time *if* the addon is installed through the addon menu.  If you just download the gut repo and copy it across manually, it won't and you may get this error.

Did you install direct from git, or via a zip file in KOD.
