### ISSUE TITLE
Plex Queue doesn't play

### ISSUE THREAD

**Issue by heinj98** [hippojay/plugin.video.plexbmc#124]
I'll post relevant data from log, but it looks like a dns resolving issue is what's hanging it up. 

01:24:09 T:1476  NOTICE: ===== PLEXBMC START [id: 1441261449.62] =====
01:24:09 T:1476  NOTICE: PleXBMC -> Reading settings configuration
01:24:10 T:1476  NOTICE: PleXBMC -> Running PleXBMC: 4.0.0~beta4
01:24:10 T:1476  NOTICE: PleXBMC -> Script argument is ['plugin://plugin.video.plexbmc/', '8', '?url=http%3A//node.plexapp.com%3A32400/system/services/url/lookup%3Furl%3Dhttp%253A%252F%252Fvimeo.com%252F137591399&mode=18&indirect=1']
01:24:10 T:1476  NOTICE: PleXBMC -> Running Python: sys.version_info(major=2, minor=7, micro=8, releaselevel='final', serial=0)
01:24:10 T:1476  NOTICE: PleXBMC -> CWD is set to: C:\Users\theater1\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix
01:24:10 T:1476  NOTICE: PleXBMC -> Platform: Windows
01:24:10 T:1476  NOTICE: PleXBMC -> Setting debug: info
01:24:10 T:1476  NOTICE: PleXBMC -> FullRes Thumbs are set to: False
01:24:10 T:1476  NOTICE: PleXBMC -> Settings streaming: 0
01:24:10 T:1476  NOTICE: PleXBMC -> Setting filter menus: True
01:24:10 T:1476  NOTICE: PleXBMC -> Flatten is: 0
01:24:10 T:1476  NOTICE: PleXBMC -> Setting stream Control to : PLEX CONTROL
01:24:10 T:1476  NOTICE: PleXBMC -> Force DVD playback: False
01:24:10 T:1476  NOTICE: PleXBMC -> SMB IP Override: False
01:24:10 T:1476  NOTICE: setting: nasoverrideip is :
01:24:10 T:1476  NOTICE: PleXBMC -> NAS IP:
01:24:10 T:1476  NOTICE: PleXBMC.plex -> load_tokencache : plexhome_cache data loaded successfully
01:24:10 T:1476  NOTICE: PleXBMC.plex -> setup_user_token : No user set.  Will default to admin user
01:24:10 T:1476  NOTICE: PleXBMC.plex -> setup_user_token : myplex userid: heinj98
01:24:10 T:1476  NOTICE: PleXBMC.plex -> setup_user_token : effective userid: heinj98
01:24:10 T:1476  NOTICE: PleXBMC -> Detected parameters: {'url': 'http%3A//node.plexapp.com%3A32400/system/services/url/lookup%3Furl%3Dhttp%253A%252F%252Fvimeo.com%252F137591399', 'indirect': '1', 'mode': '18'}
01:24:10 T:1476  NOTICE: PleXBMC.plex -> load : Loading cached server list
01:24:10 T:1476  NOTICE: PleXBMC -> Mode: 18
01:24:10 T:1476  NOTICE: PleXBMC -> URL: http://node.plexapp.com:32400/system/services/url/lookup?url=http%3A%2F%2Fvimeo.com%2F137591399
01:24:10 T:1476  NOTICE: PleXBMC -> Name:
01:24:10 T:1476  NOTICE: PleXBMC -> identifier: None
01:24:10 T:1476  NOTICE: PleXBMC.plex -> get_server_from_ip : Not an IP Address
01:24:10 T:1476  NOTICE: setting: masterServer is :
01:24:10 T:1476  NOTICE: setting: quality_uni is :
01:24:10 T:1476   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: need more than 1 value to unpack
                                            Traceback (most recent call last):
                                              File "C:\Users\theater1\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "C:\Users\theater1\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plexbmc.py", line 4243, in start_plexbmc
                                                videoPluginPlay(param_url,param_identifier,param_indirect)
                                              File "C:\Users\theater1\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plexbmc.py", line 1410, in videoPluginPlay
                                                session, vids=server.get_universal_transcode(vids)
                                              File "C:\Users\theater1\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-helix\resources\lib\plexserver.py", line 474, in get_universal_transcode
                                                resolution, bitrate = settings.get_setting('quality_uni').split(',')
                                            ValueError: need more than 1 value to unpack
                                            -->End of Python script error report<--
01:24:10 T:364   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.plexbmc/?url=http%3A//node.plexapp.com%3A32400/system/services/url/lookup%3Furl%3Dhttp%253A%252F%252Fvimeo.com%252F137591399&mode=18&indirect=1]
01:24:10 T:1172  NOTICE: Thread BackgroundLoader start, auto delete: false
01:24:15 T:588  NOTICE: Thread FileCache start, auto delete: false
01:26:43 T:1004  NOTICE: Thread JobWorker start, auto delete: true

**Comment by hippojay** [comment]
Thanks. This is a known plexbmc error with bitrates. It'll be fixed in the next version.

**Comment by heinj98** [comment]
Great,

Thanks man.  I love this addon.  Great to hear that you know what the problem is and that you're going to fix it.  That's great news.  I couldn't live without this addon.
