### ISSUE TITLE
Plex Home should not automatically log in user with PIN

### ISSUE THREAD

**Issue by QuaqSim** [hippojay/plugin.video.plexbmc#125]
1. Have Plex Media Server running, logged in with a Plex Pass subscription and multiple users (managed is fine)
2. Log in to the web interface using a plex.tv account and set a PIN
3. Log in to the same plex.tv account with plexbmc
4. Quit Kodi
5. Launch Kodi
6. >> User is logged in without having to enter PIN

As with Plex Home Theater and Plex for Android, when logging into plexbmc using a plex.tv account which has a PIN set, user selection should be presented when starting Kodi (or when choosing Go Plex) instead of signing into the user.

**Comment by phairplay** [comment]
Would really like to see this added

**Comment by joswart** [comment]
I agree. This one is an absolute showstopper.

**Comment by hippojay** [comment]
Quite right.  Problem is the lack of control over the kodi client in some areas - plus addons are stateless which means I have no way of knowing if you have just turned kodi on, whether you have finished watching a film, or have just clicked on a menu item.

To overcome this, I need to add some new services to run in the background to handle authentication.  This means I'll know exactly when it's time to pull up the drawbridge and present a pin screen. This is something I will be working on soon.
