### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Plex'

### ISSUE THREAD

**Issue by johnmaia** [hippojay/plugin.video.plexbmc#126]
17:20:30 T:2851697680  NOTICE: ===== PLEXBMC START [id: 1441556430.21] =====
17:20:30 T:2851697680  NOTICE: PleXBMC -> Reading settings configuration
17:20:31 T:2851697680  NOTICE: PleXBMC -> Running PleXBMC: 4.0.0~beta4
17:20:31 T:2851697680  NOTICE: PleXBMC -> Script argument is ['plugin://plugin.video.plexbmc/', '6', '?content_type=video']
17:20:31 T:2851697680  NOTICE: PleXBMC -> Running Python: sys.version_info(major=2, minor=7, micro=3, releaselevel='final', serial=0)
17:20:31 T:2851697680  NOTICE: PleXBMC -> CWD is set to: /home/kodi/.kodi/addons/plugin.video.plexbmc-helix
17:20:31 T:2851697680  NOTICE: PleXBMC -> Platform: Linux/RPi
17:20:31 T:2851697680  NOTICE: PleXBMC -> Setting debug: debug
17:20:31 T:2851697680  NOTICE: PleXBMC -> FullRes Thumbs are set to: False
17:20:31 T:2851697680  NOTICE: PleXBMC -> Settings streaming: 0
17:20:31 T:2851697680  NOTICE: PleXBMC -> Setting filter menus: True
17:20:31 T:2851697680  NOTICE: PleXBMC -> Flatten is: 0
17:20:31 T:2851697680  NOTICE: PleXBMC -> Setting stream Control to : PLEX CONTROL
17:20:31 T:2851697680  NOTICE: PleXBMC -> Force DVD playback: False
17:20:31 T:2851697680  NOTICE: PleXBMC -> SMB IP Override: False
17:20:31 T:2851697680  NOTICE: setting: nasoverrideip is :
17:20:31 T:2851697680  NOTICE: PleXBMC -> NAS IP:
17:20:31 T:2851697680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'Plex'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 11, in <module>
                                                import plexbmc
                                              File "/home/kodi/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 4005, in <module>
                                                plex_network=plex.Plex(load=False)
                                            AttributeError: 'module' object has no attribute 'Plex'
                                            -->End of Python script error report<--
17:20:31 T:3035213824   ERROR: GetDirectory - Error getting plugin://plugin.video.plexbmc/?content_type=video
17:20:31 T:3035213824   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexbmc/?content_type=video) failed
17:20:31 T:2851697680  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by hippojay** [comment]
This looks a like an installation issue.  Was this installed from the zip or by cloning the git repo?

**Comment by hippojay** [comment]
I'm going to chalk this up as an installation error., as the plex module is well tested as a core part of the addon.

**Comment by hippojay** [comment]
Just come across this myself.  Caused by old .pyo files (byte code python) being left behind and executed ahead of teh modified files.  Not sure why, but it's definitely not an plexbmc coding issue.
