### ISSUE TITLE
PleXBMC V4.0.0~beta4 will not resume on transcoded streams from shared libraries

### ISSUE THREAD

**Issue by dspayne1** [hippojay/plugin.video.plexbmc#130]
Beta 4 will not resume or remember position when playing transcoded media from shared libraries.

**Comment by hippojay** [comment]
I take it that non-transcoded media from shared libraries remembers positions?  I don't think have any shared libs to test with at the moment.

 I'm not sure of the status of timeline updates into another users plex server - is this allowed?  I'll have to check.

**Comment by dspayne1** [comment]
Yes, non-transcoded media from shared libraries remember the position.  

And when using the plex app it remembers shared library positions whether transcode or not.

**Comment by hippojay** [comment]
Thanks - I'll check it out then, should be reasonably easy to track down.

**Comment by gdachs** [comment]
@hippojay: do you still need access to a shared library?

**Comment by cassioac** [comment]
I mainly use shared library (cousin, mother, friends, etc...)

**Comment by gdachs** [comment]
@cassioac: I don't understand your message. Is this an answer to my question? Are you hippojay?

**Comment by cassioac** [comment]
Sorry, just ignore me, I misread your post lol
