### ISSUE TITLE
Plexbmc images cache

### ISSUE THREAD

**Issue by davboc** [hippojay/plugin.video.plexbmc#131]
Hi everyone,

I use Kodi with Plexbmc, I see that after a few days when I open movies section it restart to cache all thumbnails of the movies, and it take a lot of time.
There is a way to make more stable this kind of cache? In order to save locally the images and no need to reload them again from the server.

Thank you all.

**Comment by hippojay** [comment]
Yeah. Kodi caching is supposed to check if the image is older than 24 hours, but I've never really managed to verify this - quite often it would continue to use old images.  A random number was inserted into the image url to try and force kodi to check for updates, but I've not noticed excess ing re caching of images on the library pages. On the home page shelves then there is definitely some recaching going on, which I need to investigate.

Are you noticing this on the home page or within libraries?

**Comment by davboc** [comment]
I noticing this on the libraries, expecially movie libraries

**Comment by hippojay** [comment]
Thanks. I'll investigate.

**Comment by davboc** [comment]
Now I think that the problem is server-side not client-side. After the load of ALL thumbnails they remain in cache for a few days, after that it needs to recache all of them. I think that the problem is in the planned operations settings, under server settings of plex, I can exclude "remove old entry cache" options, but I can't find the solution...

**Comment by davboc** [comment]
After thousands of tests I can confirm that the option that generates this problem is "Refresh local metadata every three days" under server settings->scheduled tasks. I think that this is not a normal behavoir, I don't know how I can report this to the Plex developer team

**Comment by hippojay** [comment]
Thanks.  Perhaps it's a combination of plex and kodi caching.  I'll have to investigate further.

**Comment by davboc** [comment]
Not only for kodi; indeed when Kodi loses previews, I lose them in browser pc, android app and every client.
However since I deselected that option, all works well.
