### ISSUE TITLE
. I have android kodi 15.1 can not run propperly plexmbc...  I downloaded 4 beta 4!!! Not working all i get is myplex queue, signout and refresh data...

### ISSUE THREAD

**Issue by jeiai** [hippojay/plugin.video.plexbmc#132]
Cassioac please help... I have android kodi 15.1 can not run propperly plexmbc...

I downloaded 4 beta 4!!! Not working all i get is myplex queue, signout and refresh data...

And in cant do nothing please help...

**Comment by jeiai** [comment]
![screenshot_2015-10-20-08-39-07](https://cloud.githubusercontent.com/assets/15215502/10612649/efcd7164-770e-11e5-968b-b2b1d9857bce.png)

**Comment by NightShaman** [comment]
Are you connected by IP address to your internal server? Or are you trying to to log in and go through the web with a login? I had an issue where I kept losing my plex until I put in the IP address. I am also running Kodi on android with Beta 4.

**Comment by jeiai** [comment]
Thanx


Enviado por Outlook para Android





On Fri, Nov 6, 2015 at 7:40 PM -0800, "NightShaman" <notifications@github.com> wrote:












Are you connected by IP address to your internal server? Or are you trying to to log in and go through the web with a login? I had an issue where I kept losing my plex until I put in the IP address. I am also running Kodi on android with Beta 4.

**Comment by hippojay** [comment]
Is this still an issue?  if so, I'll probably need some more information about what you have set up to work out if there is an issue and where it might be.

**Comment by joswart** [comment]
Noticed the same behavior. Seems that switching "Secure Connections" from "required" to "preferred" makes all the sources visible again.

The plex log file lists the following:
00:33:02 T:140450488887040   ERROR: /home/***********/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
00:33:03 T:140449355122432  NOTICE: ===== PLEXBMC STOP [id: *****.99]: 2.06923604012 seconds =====
00:33:03 T:140450488887040  NOTICE: ===== PLEXBMC STOP [id: *****.51]: 1.93596410751 seconds =====

**Comment by hippojay** [comment]
4.0.0b4 does not support https traffic. There is a testing branch where this has been fixed (and confirmed), but it is not yet released.

**Comment by everystone** [comment]
@joswart Thank you! I just installed osmc and plexbmc for the first time, and could not figure out why it didn't work. Changing the Secure connections to prefered solved it.

**Comment by sfjuocekr** [comment]
Discovery is a problem in beta 4, selecting the server manually works and afterwards you can set it to auto and it keeps on working.
