### ISSUE TITLE
Marked as watched? 

### ISSUE THREAD

**Issue by NightShaman** [hippojay/plugin.video.plexbmc#135]
Is there a way to mark an episode as watched? I am using Kodi for android, I know in the plex app you can mark a show as watched. I have not been able to find it in the Amber skin at all.

**Comment by hippojay** [comment]
Hi. Yes - in kodi you can use the context menu to do this. How you access it will depend on the interface you are using, but generally a right click on the item (or press 'c' on a keyboard) will bring it up.

Then select "mark as watched".

**Comment by NightShaman** [comment]
Ok thanks! it's a issue on my end then as I cant quite pull up that menu using Nvidia Shield, at least not yet thanks for the reply!

**Comment by hippojay** [comment]
Not sure if this is any help:
https://forums.geforce.com/default/topic/844027/shield-android-tv/context-menu-in-kodi-/
