### ISSUE TITLE
Script error - Remote Play from Web or Andpoid App

### ISSUE THREAD

**Issue by Kazter** [hippojay/plugin.video.plexbmc#137]
Hello together,

I hope someone can help me get this thing working correctly. When trying to stream music from Plex App or Websurface to Kodi (PleXBMC) I get a script error. 

I am using:
Kodi 14.2 (OpenElec for Raspberry Pi 2)
PleXBMC 4.0.0. beta 4
PleXBMC Helper 3.4.7
Plex Server Version 0.9.14.1
Plex Web Version 2.4.23 

In the following I copied a part from the log file. Something migt be strange with the IP address when using "-" instaed of "."? I think the problem lies there. Thank you very much for your help.

07:56:18 T:1627386944  NOTICE: PleXBMC.plex -> load : Server list is now: {'c7f1ee9b5e245eee3f79541b114905d5ae72f742': <plexserver.PlexMediaServer instance at 0x6b97fe90>}
07:56:18 T:1627386944  NOTICE: PleXBMC -> Mode: 5
07:56:18 T:1627386944  NOTICE: PleXBMC -> URL: https://192-168-1-110.74d915b907ad468c8537074ea45778a9.plex.direct:32400/library/metadata/245325
07:56:18 T:1627386944  NOTICE: PleXBMC -> Name:
07:56:18 T:1627386944  NOTICE: PleXBMC -> identifier: None
07:56:18 T:1627386944  NOTICE: PleXBMC.plex -> get_server_from_ip : IP to lookup: 192-168-1-110.74d915b907ad468c8537074ea45778a9.plex.direct:32400
07:56:18 T:1627386944  NOTICE: PleXBMC.plex -> get_server_from_ip : Not an IP Address
07:56:18 T:1627386944  NOTICE: PleXBMC -> getXML : == ENTER ==
07:56:18 T:1627386944  NOTICE: PleXBMC.plex -> get_server_from_ip : IP to lookup: 192-168-1-110.74d915b907ad468c8537074ea45778a9.plex.direct:32400
07:56:18 T:1627386944  NOTICE: PleXBMC.plex -> get_server_from_ip : Not an IP Address
07:56:18 T:1627386944  NOTICE: PleXBMC.plexserver -> processed_xml : We have been passed a full URL. Parsing out path
07:56:18 T:1627386944  NOTICE: PleXBMC.plexserver -> talk : URL is: /library/metadata/245325
07:56:18 T:1627386944  NOTICE: PleXBMC.plexserver -> talk : Server: 127.0.0.1 is offline or uncontactable. error: HTTPConnectionPool(host='127.0.0.1', port=32400): Max retries exceeded with url: /library/metadata/245325?X-Plex-Platform=KODI&X-Plex-Client-Platform=KODI&X-Plex-Device-Name=My+PleXBMC+Client&X-Plex-Provides=player&X-Plex-Model=unknown&X-Plex-Platform-Version=Linux%2FRPi&X-Plex-Client-Identifier=82c0a390-4d33-4421-97e0-fc0ddbfb08d0&X-Plex-Device=PleXBMC&X-Plex-Product=PleXBMC&X-Plex-Language=en&X-Plex-Version=4.0.0~beta4 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x6b9b2f30>: Failed to establish a new connection: [Errno 111] Connection refused',))
07:56:18 T:1627386944  NOTICE: PleXBMC.plexserver -> processed_xml : PARSE: it took 0.00 seconds to parse data from 127.0.0.1
07:56:18 T:1627386944  NOTICE: PleXBMC -> getAudioSubtitlesMedia : == ENTER ==
07:56:18 T:1627386944  NOTICE: PleXBMC -> getAudioSubtitlesMedia : Gather media stream info
07:56:18 T:1627386944  NOTICE: PleXBMC -> getAudioSubtitlesMedia : No Video data found
07:56:18 T:1627386944   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('type',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 4213, in start_plexbmc
                                                playLibraryMedia(param_url,force=force, override=play_transcode)
                                              File "/storage/.kodi/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 1117, in playLibraryMedia
                                                if force and streams['type'] == "music":
                                            KeyError: ('type',)
                                            -->End of Python script error report<--
07:56:19 T:1546646592  NOTICE: PleXBMC Helper -> jsonrpc: Sending request to XBMC without network stack: {"jsonrpc": "2.0", "id": 1, "method": "Player.GetActivePlayers"}
07:56:19 T:1546646592  NOTICE: PleXBMC Helper -> parseJSONRPC: Response from XBMC: {"id":1,"jsonrpc":"2.0","result":[]}
07:56:19 T:1780479040  NOTICE: Previous line repeats 1 times.
07:56:19 T:1780479040  NOTICE: PleXBMC Helper -> jsonrpc: Sending request to XBMC without network stack: {"jsonrpc": "2.0", "id": 1, "method": "Player.GetActivePlayers"}
07:56:19 T:1780479040  NOTICE: PleXBMC Helper -> parseJSONRPC: Response from XBMC: {"id":1,"jsonrpc":"2.0","result":[]}
07:56:20 T:1780479040  NOTICE: Previous line repeats 1 times.
07:56:20 T:1780479040  NOTICE: PleXBMC Helper -> jsonrpc: Sending request to XBMC without network stack: {"jsonrpc": "2.0", "id": 1, "method": "Player.GetActivePlayers"}
07:56:20 T:1780479040  NOTICE: PleXBMC Helper -> parseJSONRPC: Response from XBMC: {"id":1,"jsonrpc":"2.0","result":[]}
07:56:21 T:1780479040  NOTICE: Previous line repeats 1 times.
07:56:21 T:1780479040  NOTICE: PleXBMC Helper -> jsonrpc: Sending request to XBMC without network stack: {"jsonrpc": "2.0", "id": 1, "method": "Player.GetActivePlayers"}
07:56:21 T:1780479040  NOTICE: PleXBMC Helper -> parseJSONRPC: Response from XBMC: {"id":1,"jsonrpc":"2.0","result":[]}
07:56:22 T:1676452928  NOTICE: Previous line repeats 1 times.
07:56:22 T:1676452928  NOTICE: PlexGDM: Recieved UDP packet from [('192.168.1.110', 59228)] containing [M-SEARCH \* HTTP/1.1]
07:56:22 T:1676452928  NOTICE: PlexGDM: Detected client discovery request from ('192.168.1.110', 59228).  Replying
07:56:22 T:1676452928  NOTICE: PlexGDM: Sending registration data: HTTP/1.0 200 OK
                                            Content-Type: plex/media-player
                                            Resource-Identifier: a4f9eac3-75b4-44e9-a490-fbf1b740319a
                                            Name: Kodi
                                            Port: 3005
                                            Product: PleXBMC
                                            Version: 4.0.0~beta4
                                            Protocol: plex
                                            Protocol-Version: 1
                                            Protocol-Capabilities: navigation,playback,timeline
                                            Device-Class: HTPC

**Comment by hippojay** [comment]
It's caused by the new plex local plex dns naming.  I have put a fix in for DNS resolution, which may help, but I need to revisit remote play to ensure it works end to end.

**Comment by InsaneSplash** [comment]
Hello,

Was this issue ever fixed and tested to be working?

```
20:50:37 T:2942147472  NOTICE: PleXBMC.plexserver -> talk : URL is: /library/metadata/31375
20:50:37 T:2942147472  NOTICE: PleXBMC.plexserver -> talk : Server: 127.0.0.1 is offline or uncontactable. error: HTTPConnectionPool(host='127.0.0.1', port=32400): Max retries exceeded with url: /library/metadata/31375?X-Plex-Platform=KODI&X-Plex-Client-Platform=KODI&X-Plex-Device-Name=My+PleXBMC+Client&X-Plex-Provides=player&X-Plex-Model=unknown&X-Plex-Platform-Version=Linux%2FRPi&X-Plex-Client-Identifier=95c1acf3-6c22-47cd-b1aa-f96d64d63826&X-Plex-Device=PleXBMC&X-Plex-Product=PleXBMC&X-Plex-Language=en&X-Plex-Version=4.0.0~beta4 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xbbb28cc>: Failed to establish a new connection: [Errno 111] Connection refused',))
20:50:37 T:2942147472  NOTICE: PleXBMC.plexserver -> processed_xml : PARSE: it took 0.00 seconds to parse data from 127.0.0.1
20:50:37 T:2942147472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('type',)
                                            Traceback (most recent call last):
                                              File "/tmp/mnt/xbmc/portable_data/addons/plugin.video.plexbmc-4.0.0beta4/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/tmp/mnt/xbmc/portable_data/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 4213, in start_plexbmc
                                                playLibraryMedia(param_url,force=force, override=play_transcode)
                                              File "/tmp/mnt/xbmc/portable_data/addons/plugin.video.plexbmc-4.0.0beta4/resources/lib/plexbmc.py", line 1117, in playLibraryMedia
                                                if force and streams['type'] == "music":
                                            KeyError: ('type',)
                                            -->End of Python script error report<--
```

**Comment by tom-s** [comment]
:+1: ? same problem here

**Comment by hippojay** [comment]
Hi

Yes it is in the current Dev branch on GitHub. Sorry for not having more info to hand. I can have a look later this evening (uk time). 


Thanks
---
Hippojay

Sent on the move, so please excuse any typos.

**Comment by hugegreenbug** [comment]
Which branch is the dev branch?

**Comment by lumixen** [comment]
I fetched the latest changes from **isengard-helper-merge** branch where remote play works just fine.

**Comment by gentle9** [comment]
Where can I find the dev branch or how can I fix that? Everything else is working fine
