### ISSUE TITLE
PLEX user sections not appearing when signed in via PLEX authenticated app

### ISSUE THREAD

**Issue by stueeey666** [hippojay/plugin.video.plexbmc#138]
with the latest Git commits on the 'Insengard-fixes' branch, I am no-longer able to see my 'individual user sections' when I sign in (via PlexMBC) and authenticate the app via (PLEX).  

though they do appear when signed in with PLEX admin user.  this was working with the Helix branch.

**Comment by hippojay** [comment]
fixed
