### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by danobrooks** [hippojay/plugin.video.plexbmc#139]
I have been having some issues with authentication of Plexbmc on a OSMC setup, found the issue related to my password having an "&" symbol, removing this corrected the issues.

With the symbol was present the configuration attempted to replace it with &amp; but this would not allow the creation of a auth token. Not sure if this is a known issue or of it relates directly to the plugin or how OSMC or Plex deal with the request.

**Comment by hippojay** [comment]
Thanks - i'll check it out.  The password input is only transformed by the authorisation process, which takes the user:password and applied a base64 encoding to it.  I'll check out where it is input though, as perhaps something happens when it is passed through.
