### ISSUE TITLE
InsecureRequestWarning

### ISSUE THREAD

**Issue by fluzz** [hippojay/plugin.video.plexbmc#141]
when accessing a shared plexmedia server the below error is thrown

`NOTICE: PleXBMC -> Detected parameters: {'url': 'https://xx-xxx-xxx-xxx.xxx.plex.direct:32400/library/metadata/19249', 'force': '221', 'mode': '5'}
ERROR: /home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
                                              InsecureRequestWarning)`

hitting `https://xx-xxx-xxx-xxx.xxx.plex.direct:32400` with both curl and chrome presents no certificate errors

**Comment by hippojay** [comment]
Hi.  Currently we can't do certificate verification on the version of Python that ships with kodi.   Until kodi uses a minimum of 2.7.10 - then we need to use a number of modules with binary dependencies. 

I attempted to build these in, but this wasn't successful -and would not be universally successful - therefore the warning will be present (although it is possible to hide them).    It needs kodi to move to something higher.
