### ISSUE TITLE
PlexBMC Stops Reporting After 1st Track

### ISSUE THREAD

**Issue by Monstar316** [hippojay/plugin.video.plexbmc#143]
As per the subject, PlexBMC doesn't seem to report music playlists very well. It will report the 1st track but then stop reporting after that. It doesn't matter if it's an album or made-up playlist, the result is the same. 
I've tried both PlexPy and PlexWatch, both give the same output so I can only assume it's an issue with PlexBMC?

**Comment by deblex** [comment]
I have the exact same issue, only the music initially launched is reported through the web interface, when it skips to the next one, plexweb doesn't show anything streaming anymore.

btw thanks for your great job Hippojay
