### ISSUE TITLE
3D MVC MKV

### ISSUE THREAD

**Issue by j-r0dd** [hippojay/plugin.video.plexbmc#147]
Is there no support for 3D MVC MKV's? They just play as 2D only. They do not switch my TV to 3D mode like a 3D BluRay does.

**Comment by gdachs** [comment]
The movies are not played by plexbmc, but by kodi and kodi has no MVC support.

**Comment by mmattern76** [comment]
That is not true anymore... Kodi on Raspberry Pi 2 supports 3D MVC MKVs just fine (at least from 15.2 onwards). I can playback 3D MVC MKVs via NFS share just fine, 3D mode on TV is triggered by Kodi.

Playing back the same file via PlexBMC though falls back to 2D (even though decoder info's - displayed via 'O' shortcut during playback - shows "mvc"). 3D mode cannot be selected via OSD as well...

**Comment by gdachs** [comment]
Ah, good to know that Kodi now plays MVC, but I don't understand why you think that it is a PleXBMC bug that this files are not shown in 3D. PleXBMC does nothing with these files. It just gets an URL from the Plex Media Server and forwards it to the Kodi Player. After this PleXBMC is not involved in the process anymore. Maybe the Plex Media Server just don't stream the second track that is needed for 3D?

**Comment by mmattern76** [comment]
Is there a way to see if the correct stream is sent from Plex?
The decoder infos (with 'O') hotkey show "mmal-mvc" in both cases (via NFS and Plex). Bitrate is at ~40 MBit in both cases.
But if I understand you correctly, it's likely a bug in Kodi - failing to recognize the 3D in this playback mode?

Sent from mobile device

**Comment by saqebakhter** [comment]
Maybe a different player is used? I think plexbmc probably uses dvdplayer not sure if there is another for 3d content 


-Saqeb 






On Thu, Jan 21, 2016 at 1:58 PM -0800, "gdachs" <notifications@github.com> wrote:












Ah, good to know that Kodi now plays MVC, but I don't understand why you think that it is a PleXBMC bug that this files are not shown in 3D. PleXBMC does nothing with these files. It just gets an URL from the Plex Media Server and forwards it to the Kodi Player. After this PleXBMC is not involved in the process anymore. Maybe the Plex Media Server just doesn't stream the second track that is needed for 3D?

**Comment by gdachs** [comment]
Here you can see that PleXBMC doesn't choose the player itself: https://github.com/hippojay/plugin.video.plexbmc/blob/isengard-helper-merge/resources/lib/plexbmc.py#L1224

To see what url gets played activate Debug in PleXBMC and Kodi.

**Comment by mmattern76** [comment]
Thx - any idea how to find the source location that handles this on XBMC
side (not familiar with their code base)... I guess that the code to set 3D
mode based on filename via NFS might have to be used also for playback via
URL...

**Comment by gdachs** [comment]
I don't know where this happens in the source of kodi. You should ask this in the Kodi forum.
This issue should be closed now, and hippojay has more time to fix real bugs and could merge my changes.

**Comment by j-r0dd** [comment]
Looks like this is a Kodi issue. Closing this bug. Looks like there is some work being done to get this working. Bookmark the following link for progress. http://forum.kodi.tv/showthread.php?tid=226440
