### ISSUE TITLE
Problem with casting previously started movies

### ISSUE THREAD

**Issue by gdachs** [hippojay/plugin.video.plexbmc#150]
I try to cast a previously started movie from the plex android app to plexbmc. The app asks me whether I want to continue, or start from the beginning. If I choose to continue, the movie will not get started from plexbmc because this time plexbmc again asks me to continue, or to start from the beginning :(. Maybe something from the casting url got lost? If you could tell me how the url that get used by the player should look like, I could try to track that down. 

I don't know whether this is important for this issue, but the [patch](https://github.com/hippojay/plugin.video.plexbmc/commit/56ae451dcaf780e7bccc3abe6eaa81b97e4da4c7) that looks for "plex.direct" is active in my case.

**Comment by gdachs** [comment]
Solved with this [pull request](https://github.com/hippojay/plugin.video.plexbmc/pull/153).

**Comment by hippojay** [comment]
Thanks. Yes, I'd we start via the helper then we should prompt on screen. Will merge when I get the chance.

**Comment by hippojay** [comment]
Doh. Sorry typos. If we start from helper, we shouldn't prompt on screen.

**Comment by gdachs** [comment]
Now I understand it :)
