### ISSUE TITLE
Updates? :)

### ISSUE THREAD

**Issue by mbnn** [hippojay/plugin.video.plexbmc#151]
Hello Hippojay and others, 

I was hoping to see a new update anytime soon? :)
For example refreshing on deck sometimes doesnt work with Kodi 16.x and sometimes it refreshes to a different PMS server while another was selected as primary.

Do you think we will see a new update anytime soon? :)

Thx!

**Comment by gsterg** [comment]
Yeah totally second that. This add-on is the bomb. Would like to continue using it, but I fear the lack of support. Video quality is just so much better using this with kodi than using the native plex app in pretty much any platform (AndroidTV, FireTV). I use a projector and the slightest artifacts just jump out with the native app. Kodi and this add-on delivers better blacks and a level of configurability for video and audio settings that the native on will probably never care to support. Are there any popular forks instead that i apparently I am missing out ? hippojay dont give up on it :)

**Comment by cassioac** [comment]
Plex is now officially supported by Kodi:

http://forums.plex.tv/discussion/246911/installation-instructions
