### ISSUE TITLE
Plexbmc Errors

### ISSUE THREAD

**Issue by cassioac** [hippojay/plugin.video.plexbmc#152]
Hi, I'm trying to install Plexbmc-isengard and isengard-fixes but both gives me this error:

http://xbmclogs.com/pm74gafyf

**Comment by cassioac** [comment]
And now v4.0b4 is also throwing this different error, already reset configuration but the problem persists...

http://xbmclogs.com/p9t7bgtnu

**Comment by hippojay** [comment]
Sorry. Logs appear to have rotated out of xbmclogs.

**Comment by cassioac** [comment]
I'll make new ones and post asap, about the v4.0b4 I've solved reinstalling kodi on android
