### ISSUE TITLE
Raspberry Pi hardware acceleration causes the video to judder

### ISSUE THREAD

**Issue by afinetapestry** [hippojay/plugin.video.plexbmc#157]
I'm having trouble with PleXBMC on a Raspberry Pi. The problem is present in all versions of PleXBMC from v3.6.1 to v4.0.0b4 and the Isengard and isengard-helper-merge branch in git. I'm using Kodi v15.2 which is the most recent in the Raspbian repos.

The problem is that no settings provide a smooth video playback. The settings I have been playing with are mostly the Kodi hardware acceleration flags but I've also been trying out a few PleXBMC settings too to see if they can solve the problem.

Always transcode is on as the source is 1080p HEVC which triggers DVDPlayer to software decode (and isn't capable of doing in time.) The transcoder is universal and the quality 1080p 8mbps (I have a pretty hefty internet connection so I know that is not the cause). Force DVD Playback is off.

1. With OMXPlayer on and MMAL on OMXPlayer player stutters like it's presenting frames in DTS order instead of PTS order.
2. With OMXPlayer off and MMAL on DVDPlayer displays no picture.
3. With OMXPlayer on and MMAL off same as issue 1.
4. With OMXPlayer off and MMAL off DVDPlayer can't software decode 1080p H.264 fast enough.

Both flags must be enabled for local content (i.e. not Plex streamed) to play well, as a mixture of H.263 and H.264 content.

I do not have MPEG-2 or VC-1 keys.

I could attach a video of the issue if required?

Many thanks.

**Comment by hippojay** [comment]
Pi or Pi2?  From experience, the Pi is not a fantastic media player. I've had issues of slowness, lack of sound during playback, media not starting, etc. 

I would highly recommend getting a Pi2. I switched just after they came out and the difference is startling. Mine is used daily without any issues at all.   It's one of the best £25 I've spent.

**Comment by afinetapestry** [comment]
Sorry, I should've been more clear. Although I have a Pi1 this report is for a Pi2. I can't imagine the Pi1 coping too well with this at all.

Cheers.

**Comment by hippojay** [comment]
My Pi2 is running openelec 5 and kodi 14.2 - and I do not see any issues.   I stream 1080p content to it over my network. 

This sounds more like a kodi/raspbian issue than plexbmc. Does this happen with all media, or just hevc?

**Comment by afinetapestry** [comment]
Perhaps it is an Isengard issue? I wonder if I can find a build of 14.2 for Raspbian to try out.

I have Always Transcode enabled so everything is coming down as H.264 but it happens if the source is H.264 or HEVC.

**Comment by hippojay** [comment]
Does it work better with transcode turned off (assuming a x264 film, so no limitations on the pi2).

**Comment by afinetapestry** [comment]
I downloaded the file from PMS just to verify that it was PleXBMC only to see that same problem occurs playing the file locally! I'm sorry to have wasted your time.

It must be an issue with OMXPlayer in Kodi 15.2. It only occurs with AVC encoded files.

I guess I'll have to make a bug report in Kodi now, although it may be fixed in Jarvis, sadly there's no build of that in the repo for Raspbian yet.

Thanks again for your help and sorry for suspecting that PleXBMC was at fault.

**Comment by afinetapestry** [comment]
I upgraded Kodi on the Pi to 16.0rc1 using Michael Gorven's unstable repo and the playback issues are fixed.

There are issues with Jarvis however, such as "Go Plex" only working once per launch of Kodi and lots of  InsecureRequestWarnings and some Connection Refused but on the whole things are working well. I will close the issue now.
