### ISSUE TITLE
Donation to support updates

### ISSUE THREAD

**Issue by ghost** [hippojay/plugin.video.plexbmc#165]
Hi guys,

I am a huge fan of the plexbmc add-on but missing updates recently :(

I am not in the position to develop myself but I like to pay tribute to the developer.

Thats why my question would be if anyone else is willing to pay for this awesome plugin to support the developer? Maybe this would mean some faster updates for us and support for his hard work.

Thanks hippojay ;)

Best
Sebastian

**Comment by cassioac** [comment]
I second that thought, let’s make a crowdfunding!

Em 21 de fev de 2016, à(s) 17:56, Sebastian <notifications@github.com<mailto:notifications@github.com>> escreveu:


Hi guys,

I am a huge fan of the plexbmc add-on but missing updates recently :(

I am not in the position to develop myself but I like to pay tribute to the developer.

Thats why my question would be if anyone else is willing to pay for this awesome plugin to support the developer? Maybe this would mean some faster updates for us and support for his hard work.

Thanks hippojay ;)

Best
Sebastian

**Comment by MasothU** [comment]
I would love to see new life here. Have you asked hippojay if he is willing to further develop plexbmc?

**Comment by Tischers** [comment]
Hi, 

I thought he would answer here if he likes to invest:) 

If so I would have started a funding campaign or help him setup a donation page... 

Does anyone has an email address? 
-- 
Sebastian Tischer

**Comment by hippojay** [comment]
Hi guys. It's not money it's time at the moment. There is light at the end of the tunnel though and I think I'll be out of this mess in 3 weeks, when I close this project. 

I'd love to quit my job and write plexbmc for a living, but not sure it's a good career move :-)

**Comment by MasothU** [comment]
Nope, sorry. 
On the plex forums I saw a new fork from hippojay to solve some problems with the latest kodi. Perhaps some guys from threre will continue to develop...

**Comment by Tischers** [comment]
3 weeks sounds great :) but if we can support you at least a bit I am willing to donate something to you really!:)

@masothU: May you please send me the url to the fork? Thanks a lot :)

**Comment by saqebakhter** [comment]
Which fork is this @MasothU ?

**Comment by MasothU** [comment]
Here, they start to talk about forks
https://forums.plex.tv/discussion/106593/plexbmc-xbmc-add-on-to-connect-to-plex-media-server/p92

And the two forks I've found so far in the thread. I haven't tested any of these forks since I'm on an older kodi release where hippojays addon still works like a charme
https://github.com/neffs/plugin.video.plexbmc/tree/isengard-helper-merge
https://github.com/gritstub/plugin.video.plexbmc

So, please read the thread on the plex forum. I just scanned quickly over it and found these forks.

**Comment by hippojay** [comment]
I'm happy with forks, and I'm also happy to merge back to maintain a single repo, which is ultimately the best way to ensure that we don't get fragmentation.

**Comment by j-r0dd** [comment]
Well, money can be a great motivator. At least set up a donation on PayPal
(they keep 20%) I know from being a device maintainer for cyanogenmod back
in the day. Or set up a square Cash account for free. https://cash.me. Me
and my buddies send money to each other all the time instantly using that
app on the phone. They don't take a dime from you. Add it to your
signature.

**Comment by Tischers** [comment]
@hippojay Hi, how are you doing? Is the stress you are having over? I am asking because we miss you and the updates :) Would love to hear back, thanks a lo.

**Comment by hippojay** [comment]
Hi - sorry for the delay.  Yes the stress is over as I quit my job :)
Just started somewhere new and now i'm settled in I have free time again
\o/  .  I'm going to start looking at this again.

On 21 May 2016 at 18:27, Sebastian <notifications@github.com> wrote:

> @hippojay <https://github.com/hippojay> Hi, how are you doing? Is the
> stress you are having over? I am asking because we miss you and the updates
> :) Would love to hear back, thanks a lo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hippojay/plugin.video.plexbmc/issues/165#issuecomment-220790314>
>



-- 
Dave

**Comment by Tischers** [comment]
No need to apologize, the news that you are helping us again with this awesome software is the best we can hear :)

My offer to pay you for this is still on the table, just tell me how and I will support you any way I can :)
