### ISSUE TITLE
Multiple Plex servers

### ISSUE THREAD

**Issue by sfjuocekr** [hippojay/plugin.video.plexbmc#167]
The plugin does not properly support multiple Plex servers.

I have three Plex shares at home, but only one is found. I could swap the IP for the server to access other shares, but that is less convenient than for example just using UPnP shares.

**Comment by hippojay** [comment]
Which version of the plugin, as I test against multiple plex servers (at the moment I have two – one osx and one windows – but have had a third running on linux without issue).

**Comment by Rockycjc** [comment]
Not to hijack this thread....but to hijack this thread....Hippojay....I
assume since you have answered this thread you are actively working on a
version of Plexbmc for Jarvis !! :-)

**Comment by sfjuocekr** [comment]
The version I use is PleXBMC V4.0.0~beta4.

I have a Gentoo Linux machine, one Windows 10 laptop and my iMac from 2006.

I have Plex, Kodi (nightly build from yesterday) and this addon on all these machines. They all show the same behavior, the listed server shares is always my iMac.

There is a Raspberry Pi2 running OpenELEC and this addon, also the same result as it shows my iMac.

When I use the Plex webapp, I see all shares and can switch between them without a hitch.

I can access the shares separately if I setup the "master server" and just fill in the IP of the share(eg: 10.0.0.121).

**Comment by hippojay** [comment]
Does plexbmc not work on Jarvis?  I'm only a few weeks away from my current work assignment ending (just after Easter) and I plan to spend some one on this. 

I understand though that other forks may be around?

**Comment by hippojay** [comment]
Ok. I slightly later beta would probably help (isengard). There were issues with plex servers running on devices with multiple NICs or virtual NICs (such as vm hosts, docker hosts, vpns). Do any of these match you configurations?

**Comment by Rockycjc** [comment]
There is an isengard-helper fork that works on Jarvis but I find that the
menus lag and sometimes don't load at all.  Might be an Amber skin issue
but they have updated their skin for Jarvis and had multiple updates.
