### ISSUE TITLE
Secure Connection Mode Support please

### ISSUE THREAD

**Issue by smurfster** [hippojay/plugin.video.plexbmc#169]
Hey,

Great work on the plugin, I use it all the time.

I was wondering if you will be supporting "Secure Mode Only" plex servers in the future as when I've tried it, the plex server disappears from my list in kodi.

Cheers

**Comment by hippojay** [comment]
This should work using the latest isengard branch.

**Comment by smurfster** [comment]
brilliant, thank you for the great work and really quick response.
