### ISSUE TITLE
no local streaming with latest plex

### ISSUE THREAD

**Issue by andreasc1** [hippojay/plugin.video.plexbmc#176]
Hi, it seems that latest plex broke the plexbmc plugin, it cannot discover the local plex server. I have tried to define the ip as well. still nothing. any chance to update?

thanks

**Comment by hans-hersbak** [comment]
Maybe it's just the network settings on your plex server.
I had then same problem after I updatet my server, suddenly my client's was unable to connect to the server.

The update changes something in the "Network Authorization" settings. 

Look here, about half way down on the page. That solved the problem for my client's 
https://support.plex.tv/hc/en-us/articles/200890058-Require-authentication-for-local-network-access

"List of networks that are allowed without auth" is only visible in advanced settings..

**Comment by megahz** [comment]
thanks, ill check it out and report back.

**Comment by wiwie** [comment]
thanks @hans-hersbak , that solved my issues as well!
