### ISSUE TITLE
No library entries in XBMC remote app

### ISSUE THREAD

**Issue by polyboi** [hippojay/plugin.video.plexbmc#27]
First of all thanks heaps for all your work. I'm just wondering if there is any way to get PLEX sources to show up in the library for the remote app. As it is I can only use the "Remote Control" function on the app but it would be really nice if I could use the library functions too.

**Comment by hippojay** [comment]
At the moment there is no way to get addon source to show in the xbmc/kodi apps, as they only display the kodi library information.  The plexbmc helper was created to allow the plex based apps to control xbmc/kodi (from a plex point of view) so this would be the best route.

Hopefully one day kodi will allow drop in library replacements, but unfortunately not yet (or on the roadmap from what I can see).
