### ISSUE TITLE
Can't open plex server...

### ISSUE THREAD

**Issue by ne0ark** [hippojay/plugin.video.plexbmc#34]
When i go to Video -> Addon -> PlexBMC . I see my server listed however when I click it nothing happens. It doesn't login. I have enabled require authentication on local network.

**Comment by hippojay** [comment]
This is not behavour I can reproduce - do you have any logs from kodi that I can see.  Otherwise head to the plex forums for additional help:

https://forums.plex.tv/index.php/topic/106593-plexbmc-xbmc-add-on-to-connect-to-plex-media-server/page-42

**Comment by hippojay** [comment]
The later version (3.6.0 onwards) deals with local authentication better and so this should not be an issue. I'll close this now, but if this issue does reoccur on a later version please log a ticket again (with some debug logs) and I will investigate.
