### ISSUE TITLE
Add trailer "button" to Plexbmc

### ISSUE THREAD

**Issue by imadunatic** [hippojay/plugin.video.plexbmc#35]
Not sure if this is even possible, but if so, I'd like to make a request to have the trailer button added to the movie information screen (same behavior as default XBMC movie info page). 

Thanks for all the work on this plugin.

**Comment by olivierbossel** [comment]
+1 :)

**Comment by hippojay** [comment]
Thanks geertbongers (and Olivierbossel for making me aware) - I've just added this to plexbmc

**Comment by olivierbossel** [comment]
nice thanks :+1:

**Comment by huzz456** [comment]
Hi, currently in the plexbmc info screen there is a 'search trailer' button that takes you to the youtube addon but doesn't search. Is it possible to get a 'trailer' button that behaves the same as native kodi library by just playing the trailer directly from youtube?

**Comment by dbrgn** [comment]
I installed 4.0.0beta4, but cannot find the trailer button. Where is it supposed to be? I tried both the Amber and the Maximinimalism themes.

**Comment by icemouton** [comment]
Same here I cannot find the button using latest kodi and latest plexbmc plugin on amber

**Comment by techobrien** [comment]
Chiming in to say that I also cannot find the trailer button in plexbmc on either confluence or amber skins. Am I missing something?

**Comment by JasB19** [comment]
Also do not see the trailer button on Amber skin.
