### ISSUE TITLE
Issues with channels

### ISSUE THREAD

**Issue by Chris230291** [hippojay/plugin.video.plexbmc#36]
Hello. Thanks for the great work. The plugin mostly works great but I have come across a couple of issues.

When using the plex mobile app (iOS) to select content from within the Twitch and iPlayer channels (haven't tried others), the media fails to play. A Twitch stream will start to open with "opening stream" but then fails, and the iPlayer plugin will ask me to pick from one of several streams (I presume they are the different available quality options) but once selected they don't play either. 

Are these known issues or is there something wrong my end?
Is there any information I can give you to help resolve this issue?

Thanks,
Chris.

**Comment by hippojay** [comment]
There was an issue with a number of channels where the plex API had changed. The newer versions (3.6.0 upwards) have fixed channel issues, so hopefully this will work correctly now.

I will close the ticket on this basis, but if it reoccurs on the new version, the. Please log a ticket and I will investigate. Thanks.
