### ISSUE TITLE
Cleanup of forks

### ISSUE THREAD

**Issue by iBobik** [hippojay/plugin.video.plexbmc#37]
Hi,
what about to merge separated work to one repository? It seems that account http://github.com/plex-collective is active, has nice "collective" name, but Helix is developed there and is not default. It is not easy for new users to find correct repository and branch to install.

I recommend to migrate everything to one repository and white in readme, wiki, addon repository and forums what is active repository and what should users download.

Please discuss about it - @hippojay @austin1howard @llllllllllllll

**Comment by austin1howard** [comment]
The goal with myself and @nrgaway was to put everything in plex-collective, along with doing some serious refactoring work on plexbmc (which it is in desparate need of). For right now we were keeping everything in hippojay's repo as that's where people have been downloading it from, but to be completely honest I haven't had enough time in recent months to look at plexbmc much (day job has been pretty busy). What I would really like to do is refactor plexbmc to use the plexapi python library from the plexconnect project (https://github.com/iBaa/PlexConnect). They actually took it originally from plexbmc, but they've kept their api in much better shape than plexbmc has. So one day, when I have some time, I'd wanted to look into that, finalizing nrgaway's refactoring work (which was quite intensive), and moving things, but I just haven't had the time recently.

Would you like to help iBobik?

**Comment by iBobik** [comment]
Hi,
I can help you with cleanup of repositories, wiki, etc., migrating to
plex-collective and some other thinks, but I don’t know XBMC API, so I
can’t help with development.



Jan Pobořil

2015-02-11 21:19 GMT+01:00 Austin Howard <notifications@github.com>:

**Comment by hippojay** [comment]
Given all the complains about plexhome I started to refactor plexbmc, looking to revisit and rewrite a lot of the code.  I wrote it a looong time ago and some of it is pretty naive. 

I don't have any great attachment to the name or location of the code.  I do to the project though, I've just found it hard to devote the time. 

If you want to help ibobik - You don't need to know about the XBMC API to help out. That's probably the easier parts - it's the Plex API and the general approach that needs ideas (writing code is easy, designing it takes more thought). 

KODI addons are stateless - they have no knowledge of what has gone before - which makes them resource intensive every time they run (as they recreate their environment). I was wondering about rewriting the plex helper to provide all this information (so run, discover and collect Server/section information) which could then be passed (as objects) to the addon. This runs as a script so once running never stops. This might speed up the addon as it would need reduced time to read in the environment.   Now if someone could help with this idea that would be great. 

Thanks
---
Dave H-J

**Comment by iBobik** [comment]
I know Python, but just in web context. My knowledge is more about web
technologies and UX.

About designing, I can give you ideas how to make all things more easier
for users and some simple things can code.

If you agree we can start discuss particular topics in issue queue.



Jan Pobořil

2015-02-11 22:07 GMT+01:00 hippojay <notifications@github.com>:

**Comment by hippojay** [comment]
I'm looking to close this ticket at the moment.  i have a new v4 beta plexbmc addon which covers all the functions and I have re-visited all the plex API type code (which I think are free of any kodi specific functions).  

What I would like to do next is to look at turning the helper into the discovery and data processing portion, using the new Plex/plexserver objects, leaving the addon to simply collect this data and display it (not sure how at the moment - would prefer to pass binary object data, rather than having to re-process again.  Perhaps some http transfer of a pickled object or a shared database so it could be just pulled?). Also, I would have the helper populate the skin properties, so they could occur in the background..

**Comment by iBobik** [comment]
I am quite lost about what are you talking about - I dont know this APIs :-)

Close it.



Jan Pobořil

2015-04-27 23:31 GMT+02:00 hippojay <notifications@github.com>:

**Comment by hippojay** [comment]
Ok. I agree that finding the latest versions is not straight forward and I'll look at doing something about that.   

The API I was talking about was in respect of the plex-collective code.  All these functions are implemented in plexbmc, so migrating to use there code is not required - although is still possible (but would need some rework). 

Anyway, I'll close this for now.
