### ISSUE TITLE
Channels only play last stream of multiple stream sources.

### ISSUE THREAD

**Issue by ldamewood** [hippojay/plugin.video.plexbmc#38]
Hi, I just installed the plugin and tried to use both the South Park and Comedy Central channels. Since both services use multiple streams per episode, PleXBMC (6dc3181fa0) only plays the last stream - i.e. starting where the last commercial break would be to the end of the episode. Using the Plex App on my iphone does not have this problem, so I believe it is an issue with PleXBMC. I tried using 3.0.0, 3.4.5 and the current and I get the same results. I am using Plex Media Server 0.9.11.7.803-87d0708 and Kodi 14.0-Helix. All are running on Windows 7-x64.

**Comment by ldamewood** [comment]
Here are some more details: After turning on the debugging, the XML returned from the plex server for the URL "http://192.168.56.1:32400/system/services/url/lookup?url=http%3A%2F%2Fsouthpark.cc.com%2Ffull-episodes%2Fs01e01-cartman-gets-an-anal-probe" for the first episode of south park (S1E1) contains 4 Part tags within Media. The 4 parts correspond to the 4 acts of the episode. It appears PleXBMC only plays the last Part. Here are the two relevant lines in the debug log. After reading the entire XML file, it starts by loading the last act.

> 18:28:17 T:1316  NOTICE: PleXBMC -> getURL: ====== XML finished ======
> 18:28:17 T:1316  NOTICE: PleXBMC -> videoPluginPlay: [{'identifier': 'com.plexapp.system', 'videoResolution': '480', 'key': 'rtmpe://viacommtvstrmfs.fplive.net:1935/viacommtvstrm playpath=mp4:gsp.comedystor/com/sp/season-1/0101/acts/sp_0101_actHD_04_B_640x480_800.mp4'}, {'identifier': 'com.plexapp.system', 'videoResolution': '480', 'key': 'rtmpe://viacommtvstrmfs.fplive.net:1935/viacommtvstrm playpath=mp4:gsp.comedystor/com/sp/season-1/0101/acts/sp_0101_actHD_04_B_640x480_600.mp4'}, {'identifier': 'com.plexapp.system', 'videoResolution': '360', 'key': 'rtmpe://viacommtvstrmfs.fplive.net:1935/viacommtvstrm playpath=mp4:gsp.comedystor/com/sp/season-1/0101/acts/sp_0101_actHD_04_B_480x360_400.mp4'}, {'identifier': 'com.plexapp.system', 'videoResolution': '360', 'key': 'rtmpe://viacommtvstrmfs.fplive.net:1935/viacommtvstrm playpath=mp4:gsp.comedystor/com/sp/season-1/0101/acts/sp_0101_actHD_04_B_480x360_300.mp4'}]

**Comment by hippojay** [comment]
Thanks.  I'l be honest and say that channels are not the best looked after part of the addon.  They are difficult to manage.  I'll have a look at these multipart files - but they may be non-trivial to solve (A playlist would be the first thought, but this might introduce a large delay between parts).
