### ISSUE TITLE
plexbmc throws string exception when launching plugin

### ISSUE THREAD

**Issue by redlandmover** [hippojay/plugin.video.plexbmc#39]
it looks like plexbmc is throwing a string exception when launching plugin.

dug through the logs to find: 

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: not all arguments converted during string formatting
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 111, in <module>
                                                print "PleXBMC -> Running Python: %s" % sys.version_info
                                            TypeError: not all arguments converted during string formatting
                                            -->End of Python script error report<--

this appears to be coming from https://github.com/hippojay/plugin.video.plexbmc/blob/helix/default.py#L111

note the difference from previous versions: https://github.com/hippojay/plugin.video.plexbmc/blob/v3.4.6beta3/default.py#L66

**Comment by hippojay** [comment]
Thanks - fix added

**Comment by Rockycjc** [comment]
Good news!!!!  Works.  But now without weirdness.  We were in the middle of
watching a kid movie but everybody left the room....so I went ahead and
upgraded the plugin.  Initially I got script failed again.. so I
Uninstalled in order to downgrade.  Then set debug mode on and quit kodi.
When I went back in to kodi I reinstalled and it worked!!!

**Comment by hippojay** [comment]
I think the script failure is related to the new debug settings in place.  The settings don't get upgraded, so when I've moved from a boolean to a list, this causes problems.  Opening settings and saving it should make it work - but i need to find a better way to make smoother upgraded.

Probably look to detect an upgrade and force a setting page to open to re-save the new settings.

**Comment by Rockycjc** [comment]
I'm cool with the workaround.  Thanks for your hard work.  I'll keep
testing when you put new builds up.
