### ISSUE TITLE
Script error when CWD has non-ascii chars.

### ISSUE THREAD

**Issue by AtliThor** [hippojay/plugin.video.plexbmc#41]
I have an issue with PlexBMC 3.4.6beta3 on Win8, when used in Kodi 14.2 (Helix Beta 1).

    17:20:10 T:12548  NOTICE: ===== PLEXBMC START =====
    17:20:10 T:12548  NOTICE: PleXBMC -> Running Python: sys.version_info(major=2, minor=7, micro=8, releaselevel='final', serial=0)
    17:20:10 T:12548  NOTICE: PleXBMC -> Running PleXBMC: 3.4.6~beta3
    17:20:10 T:12548  NOTICE: PleXBMC -> FullRes Thumbs are se to: false
    17:20:10 T:18652   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                Error Type: <type 'exceptions.UnicodeEncodeError'>
                                                Error Contents: 'ascii' codec can't encode characters in position 39-40: ordinal not in range(128)
                                                Traceback (most recent call last):
                                                  File "C:\Users\Atli߳r\AppData\Roaming\Kodi\addons\plugin.video.plexbmc-3.4.6beta3\default.py", line 69, in <module>
                                                    print "PleXBMC -> CWD is set to: " + __cwd__
                                                  File "<string>", line 7, in write
                                                UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-40: ordinal not in range(128)
                                                -->End of Python script error report<--

Note that the user path contains non-ascii characters.

By editing the line it points to there (#69 in default.py) and adding a `.encode('utf-8')`, the error is fixed and the addon seems to function correctly thereafter.

    print "PleXBMC -> CWD is set to: " + __cwd__.encode('utf-8')

**Comment by hippojay** [comment]
Hi - and thanks for the bug report.  You've reminded me that I need to check more carefully for extended charsets on inputs.  I'll get this fixed and also ensure we have better handling of this.

**Comment by hippojay** [comment]
Is fixed in the helix re-write (not yet released, but getting closer)
