### ISSUE TITLE
smb fails to play when special-char in path

### ISSUE THREAD

**Issue by wurtzelsepp** [hippojay/plugin.video.plexbmc#42]
17:51:57 T:1695409592  NOTICE: Creating InputStream
17:51:57 T:1695409592   DEBUG: CSMBFile::Open - opened FILME_U/H%C3%B6lle/H%C3%B6lle.avi, fd=-1
17:51:57 T:1695409592    INFO: SMBFile->Open: Unable to open file : 'smb://USERNAME:PASSWORD@192.168.1.16/FILME_U/H%25C3%25B6lle/H%25C3%25B6lle.avi'
                                            unix_err:'2' error : 'No such file or directory'
17:51:57 T:1695409592   ERROR: CDVDPlayer::OpenInputStream - error opening [smb://USERNAME:PASSWORD@192.168.1.16/FILME_U\H%C3%B6lle\H%C3%B6lle.avi]
17:51:57 T:1695409592  NOTICE: CDVDPlayer::OnExit()

So Chars like "ÖÄÜ,öäü" seems to be not supported useing smb protokoll.

**Comment by wurtzelsepp** [comment]
they are also wrong displayed in movies dicription

**Comment by hippojay** [comment]
ok - this should be fixed now.  the problem was that the characters had been encoded in the plex data for URLs.  once I unquoted them, all was ok.

**Comment by wurtzelsepp** [comment]
ok n1 i have tested it it woks great
