### ISSUE TITLE
Abandoned? Error launching with Kodi

### ISSUE THREAD

**Issue by kenetik** [hippojay/plugin.video.plexbmc#43]
See title.

**Comment by hippojay** [comment]
Nope - but hasn't kept pace with the recent times.  It does work with KODI however - but withuot any logs then I can't help you understand why you can't

If you need help getting it going, head over to:

https://forums.plex.tv/index.php/topic/106593-plexbmc-xbmc-add-on-to-connect-to-plex-media-server/
