### ISSUE TITLE
Fanart and Poster Loading slow PLEX 0.9.11.14

### ISSUE THREAD

**Issue by wurtzelsepp** [hippojay/plugin.video.plexbmc#48]
Hi i dont know if it is an plex server issue or the plugin needs some adaption the posters and fanarts are loading slow so i have to select a movie and w8 until it cames a few seconds ... when it is cached its fine but i dont know how big the cache can get ...

**Comment by hippojay** [comment]
Thanks.  I had noticed it, but wasn't at the top of my list.  However it was an easy fix i the end.
