### ISSUE TITLE
Not all thumbs are being DL'ed correctly

### ISSUE THREAD

**Issue by desean1625** [hippojay/plugin.video.plexbmc#55]
12:07:35 T:2693788704   ERROR: COMXImageFile::ReadFile special://masterprofile/Thumbnails/0/06d29216.jpg m_image_size zero
12:07:35 T:2693788704  NOTICE: LoadJpeg: unable to load special://masterprofile/Thumbnails/0/06d29216.jpg

osmc@osmc:~/.kodi/userdata/Thumbnails/0$ ls -l 06d29216.jpg
-rw-r--r-- 1 osmc osmc 0 Mar 20 18:47 06d29216.jpg
osmc@osmc:~/.kodi/userdata/Thumbnails/0$

Building Recent window url: ActivateWindow(Pictures, plugin://plugin.video.plexbmc/?url=http://192.168.2.141:32400/recentlyAdded&mode=16,return
                                                Building Recent window thumb: http://192.168.2.141:32400/photo/:/transcode?url=http%3A%2F%2Flocalhost%3A32400%2Flibrary%2Fmetadata%2F3073%2Fthumb%2F1426132590&width=400&height=400&X-Plex-Platform=KODI&X-Plex-Client-Platform=KODI&X-Plex-Device-Name=My+PleXBMC+Client&X-Plex-Provides=player&X-Plex-Model=unknown&X-Plex-Platform-Version=Linux%2FRPi&X-Plex-Client-Identifier=8ff730fe-9655-4e59-aa62-67c2d5d15e01&X-Plex-Device=PleXBMC&X-Plex-Product=PleXBMC&X-Plex-Language=en&X-Plex-Version=3.6.0
12:00:41 T:2801988640  NOTICE: PleXBMC -> fullShelf : Found a recent movie entry: [I Origins]
12:00:41 T:2801988640  NOTICE: PleXBMC -> getLinkURL : Path is /library/metadata/2284
12:00:41 T:2801988640  NOTICE: PleXBMC -> getLinkURL : Detected base path link
12:00:41 T:2801988640  NOTICE: PleXBMC -> fullShelf :  Building Recent window title: I Origins
                                                Building Recent window url: plugin://plugin.video.plexbmc?url=http://192.168.2.141:32400/library/metadata/2284&mode=11&t=2253481369
                                                Building Recent window thumb: http://192.168.2.141:32400/photo/:/transcode?url=http%3A%2F%2Flocalhost%3A32400%2Flibrary%2Fmetadata%2F2284%2Fthumb%2F1420972609&width=400&height=400&X-Plex-Platform=KODI&X-Plex-Client-Platform=KODI&X-Plex-Device-Name=My+PleXBMC+Client&X-Plex-Provides=player&X-Plex-Model=unknown&X-Plex-Platform-Version=Linux%2FRPi&X-Plex-Client-Identifier=8ff730fe-9655-4e59-aa62-67c2d5d15e01&X-Plex-Device=PleXBMC&X-Plex-Product=PleXBMC&X-Plex-Language=en&X-Plex-Version=3.6.0

**Comment by hippojay** [comment]
The "unable to load" error message is from KODI attempted to read from its image cache. Plexbmc has no control over this. 

KODI should roll with this and then go directly to the source to download a copy. Did the image display?

**Comment by hippojay** [comment]
Also - what model pi is this?  I've seen plenty of issues in the past with the b/b+ When using rasp mc - It was really slow and media sometimes didn't play.. The pi2 however is a massive step up.

**Comment by desean1625** [comment]
Pi2 running OSMC

**Comment by desean1625** [comment]
I have a b+ running raspbmc and a old version of plexbmc and that all has been very stable so i froze the software for that.

**Comment by hippojay** [comment]
Just being seeing if I can recreate this - but I'm not able to.  My theories are one of the following:
1. plexbmc did not give the correct URL to download the image and therefore zero size
2. Plex was not able to serve up the image
3. Kodi was not able to cache the image

Seeing as I'm not had an instance of this, I think it's more likely that 2 or 3 occurred.  If this happens again, then I need to know:

a) whether the image displayed 
b) what the kodi.log said about trying to initially access the image
c) what Plex Media Server.log said about trying to serve up the image.

Between those two logs files should be the answer..

**Comment by desean1625** [comment]
Strange part is those thumbs were there before. They were downloaded by plexbmc on an older version I installed from zip a new version powered down to move it to a different room then after boot up this happened.

**Comment by hippojay** [comment]
Two things KODI does.  The thumbs will only be cached for 24 hours until they are checked again (I think, it's been 2-3 years since I looked at the kodi Image cache code).

Next, when KODI checks the cache, it uses the whole URL to check against, including the arguments at the end.  So if you modify any of these the image is re-downloaded.  So change the client name or uuid  and it's cached again.

**Comment by hippojay** [comment]
I've just tried to recreate and I'm not able.  I zapped my thumbnails and restarted kodi.  I then went through a short section and saw theimages cached.  I then deleted and recreated with a zero byte length.  Kodi didn't complain (it didn't show the image either, which is expected).

I then restarted kodi and it still isn't complaining about the zero byte image.  

Note that this is on windows with kodi 14.1.  Not sure what OSMC is using, perhaps 14.2 rc?

**Comment by desean1625** [comment]
Yeah, it is something weird with plexbmc. older versions work correctly. I will roll through your commits when I get a chance and let you know which one it breaks on.

**Comment by desean1625** [comment]
Might have something to do with transcoding the images... I run the plex server on an arm processor NAS so it cannot transcode.

**Comment by desean1625** [comment]
Not sure what the issue was. all commits appear to work.
