### ISSUE TITLE
Can't launch PleXBMC throught the addon menu, but can through add-on info

### ISSUE THREAD

**Issue by coach0742** [hippojay/plugin.video.plexbmc#57]
So I'm having a really weird issue with the add-on. If I try to launch it normally through the Video Add-ons menu, I get a script error and this is the logs:  
  
     01:19:19 T:2516  NOTICE: ===== PLEXBMC START =====
    01:19:19 T:2516  NOTICE: PleXBMC -> Running Python: sys.version_info(major=2, minor=7,     micro=5, releaselevel='final', serial=0)
    01:19:19 T:2516  NOTICE: PleXBMC -> Running PleXBMC: 3.5.5
    01:19:19 T:2516  NOTICE: PleXBMC -> FullRes Thumbs are se to: false
    01:19:19 T:2516  NOTICE: PleXBMC -> CWD is set to: C:\Users\Alpha C     Console\AppData\Roaming\XBMC\addons\plugin.video.plexbmc-amber
    01:19:19 T:2516  NOTICE: PleXBMC -> Platform: Windows
    01:19:19 T:2516  NOTICE: PleXBMC -> Debug is turned off.  Running silent
    01:19:19 T:2516   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                Error Type: <type 'exceptions.IndexError'>
                                                Error Contents: list index out of range
                                                Traceback (most recent call last):
                                                 File "C:\Users\Alpha Console\AppData\Roaming\XBMC\addons\plugin.video.plexbmc-amber\default.py", line 5250, in <module>
                                                    if str(sys.argv[1]) == "skin":
                                                IndexError: list index out of range
                                                -->End of Python script error report<--  
  
However, If I go into the context menu, and Add-on information, I can hit launch there and it works just fine. I also can add my libraries as favorites, and it will load them just fine.  
  
The most strange thing about this, is that it was all working fine yesterday, but now, without any changes, it doesn't.  

If you need any more info let me know. 

Thanks for all your work on this.

**Comment by hippojay** [comment]
You're running 3.5.5 - plugin.video.plexbmc-amber.   
Is this right?    

Most people reporting issues are doing so for the alpha 3.6.0 helix version. Just wanted to make sure what version you expected to be running.

**Comment by coach0742** [comment]
Sorry, I tried several versions with the same issue on the newest one. I must have copied that log when I was testing an older one. I am running the newest changes in the helix branch.

**Comment by hippojay** [comment]
I've put some input validation on these variables, so at a minimum it shouldn't error out at much.  Might still not work correctly though, as I'm not sure what arguments are being fed into the script.  I'd need to see some debug logs (plexbmc set to debug is enough)

**Comment by hippojay** [comment]
This bit of code that raised the error has been changed in the last few releases to check for a variable, so I'm going to close this now.  If it reoccurs, please open another ticket.  Thanks
