### ISSUE TITLE
PlexBMC only works when PMS is not signed in.

### ISSUE THREAD

**Issue by pappabetalar** [hippojay/plugin.video.plexbmc#58]
Hi

I have a peculiar problem with PlexBMC.

First i am running the latest version of Kodi for arm on a fully updated minix and the latest PMS for windows on a Windows server 2012. PlexBMC version 3.4.5

This i all on my LAN.
If my PMS server is signed in (and accessible from the outside). Settings - Server - General - Signed in with my Plex pass. (Lifetime member)
PlexBMC cannot access my PMS. I looked at the logs and PlexBMC is reporting wrong username/password.
I've added my subnet to the "List of networks that are allowed without auth" no dice.

But as soon as i sign out my server(No remote access), PlexBMC can connect to it and works perfectly.
If you need more info/logs i will be happy to post.

Any help would be much appreciated.

**Comment by wurtzelsepp** [comment]
dont use 3.4.5 use the helix branche it is 3.6.1
https://github.com/hippojay/plugin.video.plexbmc/archive/helix.zip

**Comment by pappabetalar** [comment]
That did it, thank you!
