### ISSUE TITLE
Feature request: Ask to continue not finished movie

### ISSUE THREAD

**Issue by iBobik** [hippojay/plugin.video.plexbmc#59]
On Rasplex client there is one nice feature: When you stop movie in the middle, the state is saved to a server. Then when you open the same movie on another client (with same server) it will ask to play from beginning or from time you closed the movie on previous client.

**Comment by hippojay** [comment]
This is already a feature of plexbmc and has been since it was first created. You don't mention what version you are using.

I assume then that it is not working for you?   When a movie is played, the timeline information is sent back to the server and this state is stored in Plex.

**Comment by iBobik** [comment]
Sorry.

I am using current stable OSMC (Helix) and Plexmbc from helix branch.

Status is saved on Plex server, but client don’t care about it when film
begins.



Jan Pobořil

2015-04-07 11:24 GMT+02:00 hippojay <notifications@github.com>:

**Comment by nikotime** [comment]
This works perfectly using Amber on both OpenElec and Windows Helix for me. I imagine it is an issue with OSMC not being fully integrated?

**Comment by hippojay** [comment]
@iBobik If you can provide some debug logs I can have a look to see if it's something particular to your setup.  It might be that you need to refresh the listing in KODI to get the latest resume time for the media you are playing.

**Comment by hippojay** [comment]
I'm going to close this ticket as plexbmc is able to save the watched status (and also the watched status for managed users). If this is still occurring with the latest v4 then please open a new ticket with some debug logs..

Thanks

**Comment by iBobik** [comment]
Ok. I am out of my home for some weeks, so I can not test it now.



Jan Pobořil

2015-04-27 23:36 GMT+02:00 hippojay <notifications@github.com>:
