### ISSUE TITLE
Timeline support in combination with helper reports twice

### ISSUE THREAD

**Issue by martink2** [hippojay/plugin.video.plexbmc#76]
Hi, 

i am running version v3.6.1, hostname is set to PleXBMC and client name in 
the settings is also set to PleXBMC, so is the name in the helper Plugin.

When playing content the Player shows up twice in the Plex web interface 
once with the name PleXBMC and once with the name kodi. 

Since i was not able to change the name in the helper (see https://github.com/hippojay/script.plexbmc.helper/issues/11) i suspect that hte helper is reporting playing 
content under the name kodi and the plugin under the name PlexBMC or vice versa.

Thanks for the great work!

Martin

**Comment by hippojay** [comment]
Yes it a known feature :) The easiest way is to switch off monitoring form within plexbmc.  We have already discussed removing monitoring from plex helper once we are happy that plexbmc covers it.
