### ISSUE TITLE
Plex/web only shows now playing videos, not playing music

### ISSUE THREAD

**Issue by homernl82** [hippojay/plugin.video.plexbmc#79]
Hallo,

minor issue, but the now playing menu in plex/web only shows playing videos, not music when played with plexbmc.

Kind regards and thanks for the great addon :+1: 

homernl82

**Comment by hippojay** [comment]
Added/Fixed - depending on how you view it :-)  

Latest github code if you want to test, otherwise I'll issue a new beta sometime tomorrow.

**Comment by homernl82** [comment]
Hello,

thanks a lot for your work. It works perfectly. I am very happy with the 
plugin :)

Is it normal that I have to authenticate the addon again using the pin, 
after updating? I just cloned the git repo, zipped it and installed it, 
then had to sign in again. It's not a big effort, but can I prevent that 
in some way in the future?

I have one more thing on my mind:

It would be great if I could go onto a music folder, like an artist or 
an album and have a "play all" option in the context menu, like I have 
in plex/web. Also if I click on a single track in an album, only that 
one track is played. It would be awesome if it would just continue 
playing the following tracks like it does when playing local music in 
kodi. Currently, to play an album I have to go to the first track and in 
the context menu select 'play from here'. In kodi usually that would be 
the default action. Or am I missing something here?

Would you prefer me to open up a new issue for that?

Kind regards and thanks again for your awesome work.

Max
