### ISSUE TITLE
Resume function does not work

### ISSUE THREAD

**Issue by j4m** [hippojay/plugin.video.plexbmc#89]
With Beta4 all movies are played from the beginning. The resume context menu appears but it does not work.

Edit:
It only doesn't work with active Transcoding.

**Comment by hippojay** [comment]
Oh - looks like the resume time is hardcoded to 0!  I'll get it fixed.

**Comment by Dukobpa3** [comment]
Is workin' ok for me

**Comment by hippojay** [comment]
OK - fixed in latest.  Needed to force the resume time for transcoded media.
