### ISSUE TITLE
Ask to continue not finished movie not working

### ISSUE THREAD

**Issue by iBobik** [hippojay/plugin.video.plexbmc#94]
I tried this feature with Amber skin, but it not asks to continue, it starts from beginning. In Plex web interface I can see status saved. Too, in Kodi's list is icon ◑ next to movie's name. (Already reported at #59)

Here is my log:
https://dl.dropboxusercontent.com/u/3306439/kodi.log

**Comment by hippojay** [comment]
Hi. I need a log with plexbmc debug turned on. This gives me more information about what plex and plexbmc are doing.

**Comment by iBobik** [comment]
Hi, updated file.



Jan Pobořil

2015-05-09 21:49 GMT+02:00 hippojay <notifications@github.com>:

**Comment by hippojay** [comment]
Not sure what to tell you here.  Everythnig plex and plexbmc related seems to be working correctly.

* Started listing movies
* Started playback of 300: rise of an empire from the beginning
* played for 136 seconds and stopped it
* Plexbmc fed back the timeline information to Plex
* You relisted and I can see that plex supplies the viewOffset data (136000 as Plex does it in ms)
* You restarted the file and I can see that the resume point was set to 136 seconds
* However the file starts from the beginning (the monitor starts from 0 seconds).

Do you get a dialog box which lets you choose your resume point (resume 'from from beginning')?   

At the moment I would suggest an OMX player issue, not adhering to the resume data being fed through (by KODI).  One thing you could try is Amber skin in Plex mode and trying playback from the shelf.  This has to force the resume data - so would give me some more trouble shooting data.

or alternatively, if you switch on KODI debugging, then this will give a lot more player information as it starts the file and might give a message as to why it isn;t resuming.
